-- 30 kunlik so'zlar (600 ta) - word_entries jadvaliga INSERT
-- Supabase SQL Editor da ishlatish uchun
-- MUHIM: avval 04_create_word_entries.sql ni ishga tushiring

-- Avval 1-30 kunlar uchun mavjud so'zlarni tozalash
DELETE FROM word_entries WHERE day_number BETWEEN 1 AND 30;

INSERT INTO word_entries (word, day_number, meaning, example, synonym) VALUES
  ('afraid', 1, 'qo''rqqan, xavotirda', 'She was afraid of the dark room.', 'qo''rqqan'),
  ('agree', 1, 'rozi bo''lmoq, kelishmoq', 'I agree with your idea completely.', 'rozi bo''lmoq'),
  ('angry', 1, 'g''azablangan, jahli chiqqan', 'He was angry when he missed the bus.', 'g''azablangan'),
  ('arrive', 1, 'yetib kelmoq, kelmoq', 'The train will arrive at noon.', 'yetib kelmoq'),
  ('attack', 1, 'hujum qilmoq, hujum', 'The dog tried to attack the cat.', 'hujum qilmoq'),
  ('bottom', 1, 'pastki qism, tub', 'The key was at the bottom of the bag.', 'pastki qism'),
  ('clever', 1, 'aqlli, zukko', 'She is a clever student who solves problems quickly.', 'aqlli'),
  ('cruel', 1, 'shafqatsiz, qo''pol', 'It is cruel to leave animals outside in cold weather.', 'shafqatsiz'),
  ('finally', 1, 'nihoyat, oxir-oqibat', 'After hours of waiting, the bus finally came.', 'nihoyat'),
  ('hide', 1, 'yashirmoq, berkitmoq', 'The children like to hide behind the sofa.', 'yashirmoq'),
  ('hunt', 1, 'ov qilmoq, qidirmoq', 'Farmers used to hunt animals for food.', 'ov qilmoq'),
  ('lot', 1, 'ko''p, juda ko''p', 'There are a lot of books in this library.', 'ko''p'),
  ('middle', 1, 'o''rta, markaziy qism', 'She sat in the middle of the room.', 'o''rta'),
  ('moment', 1, 'lahza, bir zum', 'Please wait a moment while I check.', 'lahza'),
  ('pleased', 1, 'xursand, mamnun', 'She was pleased with her exam results.', 'xursand'),
  ('promise', 1, 'va''da bermoq, so''z bermoq', 'He promised to come on time tomorrow.', 'va''da bermoq'),
  ('reply', 1, 'javob bermoq, javob', 'She did not reply to my message.', 'javob bermoq'),
  ('safe', 1, 'xavfsiz, omon', 'Always keep your passport in a safe place.', 'xavfsiz'),
  ('trick', 1, 'hiyla, fokus', 'The rabbit played a clever trick on the lion.', 'hiyla'),
  ('well', 1, 'yaxshi, sog''lom; quduq', 'She speaks English very well.', 'yaxshi'),
  ('adventure', 2, 'sarguzasht, qo''zg''alish', 'Climbing the mountain was a great adventure.', 'sarguzasht'),
  ('approach', 2, 'yaqinlashmoq, usul', 'A strange dog approached us slowly.', 'yaqinlashmoq'),
  ('carefully', 2, 'ehtiyotkorlik bilan, diqqat bilan', 'Read the instructions carefully before starting.', 'ehtiyotkorlik bilan'),
  ('chemical', 2, 'kimyoviy modda, kimyoviy', 'Do not mix these two chemicals together.', 'kimyoviy modda'),
  ('create', 2, 'yaratmoq, hosil qilmoq', 'She created a beautiful painting last week.', 'yaratmoq'),
  ('evil', 2, 'yovuz, yomon', 'The villain in the story was truly evil.', 'yovuz'),
  ('experiment', 2, 'tajriba, sinov', 'The students did an experiment in the lab.', 'tajriba'),
  ('kill', 2, 'o''ldirmoq, yo''q qilmoq', 'The frost killed all the plants in the garden.', 'o''ldirmoq'),
  ('laboratory', 2, 'laboratoriya, tajribaxona', 'Scientists work in a laboratory every day.', 'laboratoriya'),
  ('laugh', 2, 'kulmoq, kulgu', 'Everyone laughed at the funny joke.', 'kulmoq'),
  ('loud', 2, 'baland ovozli, shovqinli', 'The music was too loud at the party.', 'baland ovozli'),
  ('nervous', 2, 'asabiy, xavotirli', 'She felt nervous before the big exam.', 'asabiy'),
  ('noise', 2, 'shovqin, ovoz', 'The children made a lot of noise outside.', 'shovqin'),
  ('project', 2, 'loyiha, reja', 'We worked on a science project together.', 'loyiha'),
  ('scare', 2, 'qo''rqitmoq, vahimaga solmoq', 'Loud thunder can scare small children.', 'qo''rqitmoq'),
  ('secret', 2, 'sir, maxfiy', 'Can you keep a secret? I have good news.', 'sir'),
  ('shout', 2, 'baqirmoq, qichqirmoq', 'Do not shout in the library, please.', 'baqirmoq'),
  ('smell', 2, 'hid, hidlamoq', 'The flowers smell very sweet in spring.', 'hid'),
  ('terrible', 2, 'dahshatli, juda yomon', 'The weather was terrible during the storm.', 'dahshatli'),
  ('worse', 2, 'yomonroq, battar', 'My cold is getting worse every day.', 'yomonroq'),
  ('alien', 3, 'begona, kosmoslik mavjudot', 'The movie was about an alien from another planet.', 'begona'),
  ('among', 3, 'orasida, ichida', 'She was the best student among all her classmates.', 'orasida'),
  ('chart', 3, 'jadval, diagramma', 'The teacher drew a chart on the board.', 'jadval'),
  ('cloud', 3, 'bulut, to''da', 'Dark clouds appeared before the rain started.', 'bulut'),
  ('comprehend', 3, 'tushunmoq, anglash', 'It is hard to comprehend this difficult text.', 'tushunmoq'),
  ('describe', 3, 'tasvirlamoq, ta''riflamoq', 'Please describe what you saw at the scene.', 'tasvirlamoq'),
  ('ever', 3, 'hech qachon, doimo', 'Have you ever visited another country before?', 'hech qachon'),
  ('fail', 3, 'muvaffaqiyatsiz bo''lmoq, rad etmoq', 'He failed the test and studied harder next time.', 'muvaffaqiyatsiz bo''lmoq'),
  ('friendly', 3, 'do''stona, mehribon', 'The new teacher was very friendly to everyone.', 'do''stona'),
  ('grade', 3, 'baho, daraja', 'She got a high grade on her English test.', 'baho'),
  ('instead', 3, 'o''rniga, buning o''rniga', 'I ordered tea instead of coffee today.', 'o''rniga'),
  ('library', 3, 'kutubxona, kitoblar to''plami', 'I borrow books from the library every week.', 'kutubxona'),
  ('planet', 3, 'sayyora, dunyo', 'Earth is the third planet from the Sun.', 'sayyora'),
  ('report', 3, 'hisobot, xabar bermoq', 'He wrote a report about climate change.', 'hisobot'),
  ('several', 3, 'bir nechta, bir qancha', 'I have visited that museum several times.', 'bir nechta'),
  ('solve', 3, 'hal qilmoq, echmoq', 'Can you solve this math problem for me?', 'hal qilmoq'),
  ('suddenly', 3, 'to''satdan, birdan', 'The lights suddenly went out during dinner.', 'to''satdan'),
  ('suppose', 3, 'faraz qilmoq, o''ylash', 'I suppose the meeting will start at nine.', 'faraz qilmoq'),
  ('universe', 3, 'koinot, borliq', 'Scientists study the universe to learn its secrets.', 'koinot'),
  ('view', 3, 'ko''rinish, manzara; qarash', 'The view from the mountain top was amazing.', 'ko''rinish'),
  ('appropriate', 4, 'mos, to''g''ri, maqsadga muvofiq', 'That dress is not appropriate for a job interview.', 'mos'),
  ('avoid', 4, 'qochmoq, oldini olmoq', 'You should avoid eating too much sugar.', 'qochmoq'),
  ('behave', 4, 'o''zini tutmoq, xulq-atvor', 'Children should behave well in public places.', 'o''zini tutmoq'),
  ('calm', 4, 'tinch, sokin, xotirjam', 'She stayed calm during the difficult situation.', 'tinch'),
  ('concern', 4, 'tashvish, qaygu; qiziqtirmoq', 'His poor health is a concern for the family.', 'tashvish'),
  ('content', 4, 'mazmun; mamnun, rozi', 'She was content with her simple life.', 'mazmun; mamnun'),
  ('expect', 4, 'kutmoq, umid qilmoq', 'I expect the package to arrive tomorrow.', 'kutmoq'),
  ('frequently', 4, 'tez-tez, ko''p marta', 'He frequently visits his grandparents on weekends.', 'tez-tez'),
  ('habit', 4, 'odat, rasm', 'Reading before bed is a good habit.', 'odat'),
  ('instruct', 4, 'o''rgatmoq, yo''riqnoma bermoq', 'The teacher instructed students to open their books.', 'o''rgatmoq'),
  ('issue', 4, 'masala, muammo; chiqarmoq', 'The main issue is the lack of clean water.', 'masala'),
  ('none', 4, 'hech biri, hech qaysi', 'None of the students passed the final exam.', 'hech biri'),
  ('patient', 4, 'sabr-qanoatli, bemor', 'You need to be patient when learning a language.', 'sabr-qanoatli'),
  ('positive', 4, 'ijobiy, musbat', 'Try to think in a positive way every day.', 'ijobiy'),
  ('punish', 4, 'jazolash, jazolamoq', 'Parents should not punish children too harshly.', 'jazolash'),
  ('represent', 4, 'vakil bo''lmoq, ifodalash', 'She was chosen to represent her school.', 'vakil bo''lmoq'),
  ('shake', 4, 'silkimoq, qaltiramoq', 'He shook her hand and introduced himself.', 'silkimoq'),
  ('spread', 4, 'tarqalmoq, yoyilmoq', 'News spreads very quickly on social media.', 'tarqalmoq'),
  ('stroll', 4, 'sekin yurmoq, sayr qilmoq', 'We took a stroll in the park after dinner.', 'sekin yurmoq'),
  ('village', 4, 'qishloq, mahalla', 'She grew up in a small village in the mountains.', 'qishloq'),
  ('aware', 5, 'xabardor, bilimli', 'Are you aware of the new school rules?', 'xabardor'),
  ('badly', 5, 'yomon ravishda, juda qattiq', 'He was badly injured in the accident.', 'yomon ravishda'),
  ('belong', 5, 'tegishli bo''lmoq, a''zo bo''lmoq', 'This book belongs to the school library.', 'tegishli bo''lmoq'),
  ('continue', 5, 'davom ettirmoq, to''xtatmasdan', 'Please continue reading from page ten.', 'davom ettirmoq'),
  ('error', 5, 'xato, yanglishish', 'There was an error in the computer program.', 'xato'),
  ('experience', 5, 'tajriba, kuzatish', 'She has ten years of teaching experience.', 'tajriba'),
  ('field', 5, 'maydon, soha', 'He works in the field of medicine.', 'maydon'),
  ('hurt', 5, 'og''riq, jarohatlash; azob bermoq', 'She hurt her knee while playing football.', 'og''riq'),
  ('judgment', 5, 'hukm, baho; ko''rish qobiliyati', 'Use good judgment when making big decisions.', 'hukm'),
  ('likely', 5, 'ehtimol, mumkin', 'It is likely to rain tomorrow afternoon.', 'ehtimol'),
  ('normal', 5, 'oddiy, me''yoriy', 'It is normal to feel nervous before exams.', 'oddiy'),
  ('rare', 5, 'kam uchraydigan, noyob', 'Snow is very rare in this part of the country.', 'kam uchraydigan'),
  ('relax', 5, 'dam olmoq, bo''shashtirmoq', 'I like to relax by listening to music.', 'dam olmoq'),
  ('request', 5, 'so''rov, iltimos; so''ramoq', 'She made a request to change her seat.', 'so''rov'),
  ('reside', 5, 'yashash, istiqomat qilish', 'He resides in a small apartment near the park.', 'yashash'),
  ('result', 5, 'natija, oqibat', 'The result of the test will come tomorrow.', 'natija'),
  ('roll', 5, 'dumalash, buralmoq', 'The ball rolled down the hill quickly.', 'dumalash'),
  ('since', 5, 'beri, chunki, shu vaqtdan', 'She has lived here since she was a child.', 'beri'),
  ('visible', 5, 'ko''rinadigan, ko''zga tashlanadigan', 'The stars are not visible on cloudy nights.', 'ko''rinadigan'),
  ('wild', 5, 'yovvoyi, qo''pol; dahshatli', 'Wild animals should not be kept as pets.', 'yovvoyi'),
  ('advantage', 6, 'ustunlik, foyda', 'Knowing two languages is a great advantage.', 'ustunlik'),
  ('cause', 6, 'sabab, turtki; sabab bo''lmoq', 'What was the cause of the fire last night?', 'sabab'),
  ('choice', 6, 'tanlov, imkoniyat', 'You have the choice to study any subject.', 'tanlov'),
  ('community', 6, 'jamoa, mahalla; jamoat', 'The whole community helped after the flood.', 'jamoa'),
  ('dead', 6, 'o''lik, hayotsiz', 'The plant died because nobody watered it.', 'o''lik'),
  ('distance', 6, 'masofa, uzoqlik', 'The distance between the two cities is 200 km.', 'masofa'),
  ('escape', 6, 'qochmoq, chiqib ketmoq', 'The bird managed to escape from its cage.', 'qochmoq'),
  ('face', 6, 'yuz, bet; duch kelmoq', 'She had to face many challenges in life.', 'yuz'),
  ('follow', 6, 'ergashmoq, izidan bormoq', 'Follow the instructions on the board.', 'ergashmoq'),
  ('fright', 6, 'qo''rquv, dahshat', 'The loud bang gave everyone a big fright.', 'qo''rquv'),
  ('ghost', 6, 'arvoh, ruh', 'Some people believe that ghosts exist.', 'arvoh'),
  ('individual', 6, 'shaxs, alohida; individual', 'Each individual student has different needs.', 'shaxs'),
  ('pet', 6, 'uy hayvoni, sevimli', 'She has a pet rabbit that she loves dearly.', 'uy hayvoni'),
  ('reach', 6, 'yetib bormoq, qo''l yetmoq', 'He reached the top of the mountain by noon.', 'yetib bormoq'),
  ('return', 6, 'qaytmoq, qaytarmoq', 'I will return the book to the library today.', 'qaytmoq'),
  ('survive', 6, 'omon qolmoq, saqlanib qolmoq', 'The plant survived despite the cold weather.', 'omon qolmoq'),
  ('upset', 6, 'xafa, bezovta; buzmoq', 'She was upset when she lost her phone.', 'xafa'),
  ('voice', 6, 'ovoz, so''z; fikr', 'She has a beautiful singing voice.', 'ovoz'),
  ('weather', 6, 'ob-havo, havo sharoiti', 'The weather today is sunny and warm.', 'ob-havo'),
  ('wise', 6, 'dono, aqliy', 'It is wise to save money for the future.', 'dono'),
  ('allow', 7, 'ruxsat bermoq, imkon bermoq', 'Parents do not allow children to stay up late.', 'ruxsat bermoq'),
  ('announce', 7, 'e''lon qilmoq, xabar bermoq', 'The teacher announced the exam results today.', 'e''lon qilmoq'),
  ('beside', 7, 'yonida, qoshida', 'She sat beside her best friend in class.', 'yonida'),
  ('challenge', 7, 'qiyinchilik, sinovdan o''tkazmoq', 'Learning a new language is a great challenge.', 'qiyinchilik'),
  ('claim', 7, 'da''vo qilmoq, talab qilmoq', 'He claimed that he did not take the money.', 'da''vo qilmoq'),
  ('condition', 7, 'holat, shart; sharoit', 'The patient is in a stable condition now.', 'holat'),
  ('contribute', 7, 'hissa qo''shmoq, yordam bermoq', 'Everyone should contribute to keeping the city clean.', 'hissa qo''shmoq'),
  ('difference', 7, 'farq, tafovut', 'What is the difference between these two words?', 'farq'),
  ('divide', 7, 'bo''lmoq, ajratmoq', 'Divide the class into four equal groups.', 'bo''lmoq'),
  ('expert', 7, 'mutaxassis, bilimdon', 'She is an expert in computer programming.', 'mutaxassis'),
  ('famous', 7, 'mashhur, taniqli', 'This city is famous for its beautiful old buildings.', 'mashhur'),
  ('force', 7, 'kuch, majburlamoq', 'Do not force anyone to do something against their will.', 'kuch'),
  ('harm', 7, 'zarar, shikast; zarar yetkazmoq', 'Smoking can cause serious harm to your health.', 'zarar'),
  ('lay', 7, 'qo''ymoq, yotqizmoq', 'She laid the book on the table carefully.', 'qo''ymoq'),
  ('peace', 7, 'tinchlik, osoyishtalik', 'After the war, people finally lived in peace.', 'tinchlik'),
  ('prince', 7, 'shahzoda, knyaz', 'The prince rode his horse through the forest.', 'shahzoda'),
  ('protect', 7, 'himoya qilmoq, asramoq', 'Wear sunscreen to protect your skin from the sun.', 'himoya qilmoq'),
  ('sense', 7, 'his, tuygu; manto', 'It makes sense to study every day.', 'his'),
  ('sudden', 7, 'to''satdan bo''ladigan, kutilmagan', 'There was a sudden change in the weather.', 'to''satdan bo''ladigan'),
  ('therefore', 7, 'shuning uchun, demak', 'He studied hard; therefore, he passed the exam.', 'shuning uchun'),
  ('accept', 8, 'qabul qilmoq, rozilik bildirmoq', 'She accepted the job offer with great joy.', 'qabul qilmoq'),
  ('arrange', 8, 'tartibga solmoq, tashkil etmoq', 'He arranged all the books on the shelf neatly.', 'tartibga solmoq'),
  ('attend', 8, 'qatnashmoq, bormoq', 'All students must attend the morning assembly.', 'qatnashmoq'),
  ('balance', 8, 'muvozanat, balans; tenglashtirmoq', 'A healthy diet helps maintain a good balance.', 'muvozanat'),
  ('contrast', 8, 'farq, qarama-qarshilik', 'There is a strong contrast between the two paintings.', 'farq'),
  ('encourage', 8, 'rag''batlantirmoq, ruhlantirmoq', 'Teachers should encourage students to ask questions.', 'rag''batlantirmoq'),
  ('familiar', 8, 'tanish, oddiy, ma''lum', 'Are you familiar with this type of question?', 'tanish'),
  ('grab', 8, 'changallamoq, ushlamoq', 'She grabbed her bag and ran to the bus.', 'changallamoq'),
  ('hang', 8, 'osmoq, ilinmoq', 'Please hang your coat on the hook by the door.', 'osmoq'),
  ('huge', 8, 'ulkan, katta', 'The new shopping mall is huge inside.', 'ulkan'),
  ('necessary', 8, 'zarur, kerakli', 'It is necessary to drink enough water daily.', 'zarur'),
  ('pattern', 8, 'naqsh, shakl; namuna', 'The dress has a beautiful flower pattern.', 'naqsh'),
  ('propose', 8, 'taklif qilmoq, taklif', 'He proposed a new solution to the problem.', 'taklif qilmoq'),
  ('purpose', 8, 'maqsad, niyat', 'What is the purpose of this meeting today?', 'maqsad'),
  ('release', 8, 'ozod qilmoq, chiqarmoq', 'The singer will release a new album next month.', 'ozod qilmoq'),
  ('require', 8, 'talab qilmoq, kerak bo''lmoq', 'This job requires five years of experience.', 'talab qilmoq'),
  ('single', 8, 'yagona, bitta; yolg''iz', 'There was not a single cloud in the sky.', 'yagona'),
  ('success', 8, 'muvaffaqiyat, erishish', 'Hard work is the key to success in life.', 'muvaffaqiyat'),
  ('tear', 8, 'yirtmoq; ko''z yoshi', 'She tore the old paper into small pieces.', 'yirtmoq; ko''z yoshi'),
  ('theory', 8, 'nazariya, faraziya', 'Einstein developed the theory of relativity.', 'nazariya'),
  ('against', 9, 'qarshi, zid', 'She voted against the new school rule.', 'qarshi'),
  ('beach', 9, 'qirg''oq, plyaj', 'We spent the day relaxing on the beach.', 'qirg''oq'),
  ('damage', 9, 'zarar, shikast; zarar yetkazmoq', 'The storm caused serious damage to the village.', 'zarar'),
  ('discover', 9, 'kashf etmoq, topmoq', 'Columbus discovered America in 1492.', 'kashf etmoq'),
  ('emotion', 9, 'his-tuygu, kechinma', 'Music can express many different emotions.', 'his-tuygu'),
  ('fix', 9, 'tuzatmoq, mahkamlamoq', 'Can you fix the broken chair leg?', 'tuzatmoq'),
  ('frank', 9, 'ochiq, samimiy, to''g''ri so''z', 'She was frank about her feelings and concerns.', 'ochiq'),
  ('identify', 9, 'aniqlash, tanib olmoq', 'Can you identify the problem in this sentence?', 'aniqlash'),
  ('island', 9, 'orol, alohida joy', 'They traveled to a small island for vacation.', 'orol'),
  ('ocean', 9, 'okean, dengiz', 'The Pacific Ocean is the largest ocean on Earth.', 'okean'),
  ('perhaps', 9, 'balki, ehtimol', 'Perhaps we can meet again next week.', 'balki'),
  ('pleasant', 9, 'yoqimli, qulay', 'The spring weather is always very pleasant.', 'yoqimli'),
  ('prevent', 9, 'oldini olmoq, to''sish', 'Washing hands helps prevent the spread of germs.', 'oldini olmoq'),
  ('rock', 9, 'tosh, qoya; tebratmoq', 'She sat on a large rock by the river.', 'tosh'),
  ('save', 9, 'tejash, saqlash; qutqarmoq', 'Try to save some money for emergencies.', 'tejash'),
  ('step', 9, 'qadam, daraja; qadam bosmoq', 'Take one step at a time when solving problems.', 'qadam'),
  ('still', 9, 'hali ham; tinch, jim', 'She still has not received an answer to her email.', 'hali ham; tinch'),
  ('taste', 9, 'ta''m, maza; tatib ko''rmoq', 'This soup has a wonderful taste.', 'ta''m'),
  ('throw', 9, 'uloqtirmoq, otmoq', 'He threw the ball to his teammate.', 'uloqtirmoq'),
  ('wave', 9, 'to''lqin; qo''l siltamoq', 'She waved goodbye as the train left the station.', 'to''lqin; qo''l siltamoq'),
  ('benefit', 10, 'foyda, manfaat; foyda ko''rmoq', 'Exercise has many health benefits.', 'foyda'),
  ('certain', 10, 'aniq, ishonchli; ba''zi', 'I am certain that she will pass the test.', 'aniq'),
  ('chance', 10, 'imkoniyat, ehtimol; tasodif', 'Give everyone a chance to speak in class.', 'imkoniyat'),
  ('effect', 10, 'ta''sir, natija; ta''sir etmoq', 'The medicine had a positive effect on the patient.', 'ta''sir'),
  ('essential', 10, 'zaruriy, asosiy, muhim', 'Water is essential for all living things.', 'zaruriy'),
  ('far', 10, 'uzoq, uzoqda', 'The school is not far from our house.', 'uzoq'),
  ('focus', 10, 'e''tibor bermoq, diqqatni jamlash', 'Try to focus on one task at a time.', 'e''tibor bermoq'),
  ('function', 10, 'vazifa, funksiya; ishlash', 'What is the function of the kidney in the body?', 'vazifa'),
  ('grass', 10, 'o''t, maysazor', 'The children played on the green grass.', 'o''t'),
  ('guard', 10, 'qorovul, himoya; himoya qilmoq', 'A security guard stands at the entrance.', 'qorovul'),
  ('image', 10, 'tasvir, rasm; obro''', 'The camera captures a clear image.', 'tasvir'),
  ('immediate', 10, 'darhol, zudlik bilan', 'The problem requires an immediate solution.', 'darhol'),
  ('primary', 10, 'asosiy, birinchi', 'Her primary goal is to finish university.', 'asosiy'),
  ('proud', 10, 'faxrli, maqtanuvchi', 'Her parents were proud of her achievements.', 'faxrli'),
  ('remain', 10, 'qolmoq, saqlanmoq', 'Only a few students remained after class.', 'qolmoq'),
  ('rest', 10, 'dam olish; qolgan qismi', 'You need to rest after working so hard.', 'dam olish; qolgan qismi'),
  ('separate', 10, 'ajratmoq, bo''lish; alohida', 'Please separate the colored clothes from white ones.', 'ajratmoq'),
  ('site', 10, 'joy, o''rin; veb-sayt', 'The construction site was busy all day.', 'joy'),
  ('tail', 10, 'dum; quyruq', 'The dog wagged its tail happily.', 'dum; quyruq'),
  ('trouble', 10, 'muammo, qiyinchilik; bezovta qilmoq', 'He got into trouble for arriving late.', 'muammo'),
  ('anymore', 11, 'endi, boshqa', 'She does not live here anymore.', 'endi'),
  ('asleep', 11, 'uxlab, uyquda', 'The baby fell asleep after drinking milk.', 'uxlab'),
  ('berry', 11, 'rezavor, meva (kichik)', 'She picked fresh berries from the garden.', 'rezavor'),
  ('collect', 11, 'yig''moq, to''plamoq', 'He collects stamps from different countries.', 'yig''moq'),
  ('compete', 11, 'musobaqa qilmoq, raqobatlashmoq', 'Students will compete in the spelling contest.', 'musobaqa qilmoq'),
  ('conversation', 11, 'suhbat, muloqot', 'We had a long conversation about our future plans.', 'suhbat'),
  ('creature', 11, 'jonzot, mavjudot', 'The forest is home to many interesting creatures.', 'jonzot'),
  ('decision', 11, 'qaror, tanlov', 'Making the right decision takes time and thought.', 'qaror'),
  ('either', 11, 'ham, yoki; ikkalasi ham', 'You can choose either tea or coffee.', 'ham'),
  ('forest', 11, 'o''rmon, daraxt', 'The forest was quiet and full of tall trees.', 'o''rmon'),
  ('ground', 11, 'er, zamin; asos', 'The children sat on the ground and ate lunch.', 'er'),
  ('introduce', 11, 'tanishtirmoq, kiritmoq', 'Let me introduce you to my best friend.', 'tanishtirmoq'),
  ('marry', 11, 'turmushga chiqmoq, uylanmoq', 'They will marry in the spring next year.', 'turmushga chiqmoq'),
  ('prepare', 11, 'tayyorlanmoq, tayyorlamoq', 'She prepared carefully for her job interview.', 'tayyorlanmoq'),
  ('sail', 11, 'yelkan; suzib ketmoq', 'The boat sailed across the calm ocean.', 'yelkan; suzib ketmoq'),
  ('serious', 11, 'jiddiy, muhim', 'This is a serious problem that needs attention.', 'jiddiy'),
  ('spend', 11, 'sarflamoq, o''tkazmoq', 'He spends a lot of time reading books.', 'sarflamoq'),
  ('strange', 11, 'g''alati, notanish', 'There was a strange noise coming from outside.', 'g''alati'),
  ('truth', 11, 'haqiqat, to''g''rilik', 'Always tell the truth, even when it is hard.', 'haqiqat'),
  ('wake', 11, 'uyg''onmoq, uyg''otmoq', 'She woke up early to study before school.', 'uyg''onmoq'),
  ('alone', 12, 'yolg''iz, bir o''zi', 'She felt alone in the big city.', 'yolg''iz'),
  ('apartment', 12, 'kvartira, turar joy', 'They moved into a new apartment last month.', 'kvartira'),
  ('article', 12, 'maqola; modda; artikl', 'She wrote an article for the school newspaper.', 'maqola; modda; artikl'),
  ('artist', 12, 'rassom, san''atkor', 'The artist painted a beautiful landscape.', 'rassom'),
  ('attitude', 12, 'munosabat, qarash', 'A positive attitude helps you succeed in life.', 'munosabat'),
  ('compare', 12, 'solishtirmoq, taqqoslamoq', 'Compare these two sentences and find the difference.', 'solishtirmoq'),
  ('judge', 12, 'sudya; hukm chiqarmoq', 'Do not judge people by their appearance.', 'sudya; hukm chiqarmoq'),
  ('magazine', 12, 'jurnal, gazeta', 'She reads a fashion magazine every month.', 'jurnal'),
  ('material', 12, 'material, xom ashyo; muhim', 'Cotton is a natural material used in clothing.', 'material'),
  ('meal', 12, 'ovqat, taom, yemak', 'Breakfast is the most important meal of the day.', 'ovqat'),
  ('method', 12, 'usul, yo''l, metod', 'The teacher uses a new method to teach grammar.', 'usul'),
  ('neighbor', 12, 'qo''shni, yonidagi', 'Our neighbor is very kind and helpful.', 'qo''shni'),
  ('professional', 12, 'professional, mutaxassis', 'She is a professional translator with many skills.', 'professional'),
  ('profit', 12, 'foyda, daromad', 'The company made a large profit last year.', 'foyda'),
  ('quality', 12, 'sifat, darajasi', 'Always choose quality over quantity.', 'sifat'),
  ('shape', 12, 'shakl, ko''rinish; shakllantirmoq', 'The cake was in the shape of a star.', 'shakl'),
  ('space', 12, 'bo''shliq, joy; kosmosli', 'There is not enough space in this room.', 'bo''shliq'),
  ('stair', 12, 'pog''ona, zinalar', 'She walked up the stairs to the third floor.', 'pog''ona'),
  ('symbol', 12, 'belgi, ramz', 'The dove is a symbol of peace.', 'belgi'),
  ('thin', 12, 'ingichka, ozg''in', 'The ice on the lake is too thin to walk on.', 'ingichka'),
  ('blood', 13, 'qon, qon quyish', 'He donated blood at the hospital last week.', 'qon'),
  ('burn', 13, 'yonmoq, kuymoq; yong''in', 'Be careful not to burn your hand on the stove.', 'yonmoq'),
  ('cell', 13, 'hujayra; kamera; uyacha', 'The human body contains trillions of cells.', 'hujayra; kamera; uyacha'),
  ('contain', 13, 'o''z ichiga olmoq, saqlash', 'This box contains important documents.', 'o''z ichiga olmoq'),
  ('correct', 13, 'to''g''ri, aniq; tuzatmoq', 'Please correct your mistakes in the essay.', 'to''g''ri'),
  ('crop', 13, 'ekin, hosil; kesmoq', 'Farmers harvest their crops in autumn.', 'ekin'),
  ('demand', 13, 'talab, so''rov; talab qilmoq', 'There is a high demand for skilled workers.', 'talab'),
  ('equal', 13, 'teng, bir xil; tenglashtirmoq', 'All students have equal rights in this school.', 'teng'),
  ('feed', 13, 'oziqlantirmoq, boqmoq', 'She feeds the birds in her garden every morning.', 'oziqlantirmoq'),
  ('hole', 13, 'teshik, chuqur', 'There is a hole in the pocket of my jacket.', 'teshik'),
  ('increase', 13, 'ko''paytirmoq, oshirmoq; o''sish', 'Exercise can increase your energy levels.', 'ko''paytirmoq'),
  ('lord', 13, 'lord, xo''jayin; Allah', 'The lord of the castle invited guests to dinner.', 'lord'),
  ('owe', 13, 'qarzdor bo''lmoq, berishi kerak bo''lmoq', 'I owe you ten dollars from last week.', 'qarzdor bo''lmoq'),
  ('position', 13, 'lavozim, holat; joy', 'She applied for the position of manager.', 'lavozim'),
  ('raise', 13, 'ko''tarmoq, tarbiyalamoq', 'She raised her hand to answer the question.', 'ko''tarmoq'),
  ('responsible', 13, 'mas''ul, javobgar', 'He is responsible for locking the office door.', 'mas''ul'),
  ('sight', 13, 'ko''rish, manzara', 'The view from the top was a beautiful sight.', 'ko''rish'),
  ('spot', 13, 'dog'', joy; payqamoq', 'She spotted a rare bird in the garden.', 'dog'''),
  ('structure', 13, 'tuzilish, qurilma', 'The structure of this building is very strong.', 'tuzilish'),
  ('whole', 13, 'butun, barcha; to''liq', 'She ate the whole pizza by herself.', 'butun'),
  ('coach', 14, 'murabbiy, avtobus; o''rgatmoq', 'The coach trained the team every morning.', 'murabbiy'),
  ('control', 14, 'nazorat qilmoq, boshqarmoq', 'You need to control your emotions in stressful times.', 'nazorat qilmoq'),
  ('description', 14, 'tavsif, tasvir, ta''rif', 'Write a description of your favorite place.', 'tavsif'),
  ('direct', 14, 'to''g''ri, bevosita; boshqarmoq', 'She gave him direct instructions for the task.', 'to''g''ri'),
  ('exam', 14, 'imtihon, sinov', 'She studied all night for the final exam.', 'imtihon'),
  ('example', 14, 'misol, namuna', 'Give an example of a sentence with this word.', 'misol'),
  ('limit', 14, 'chegara, cheklov; cheklamoq', 'There is a speed limit on this road.', 'chegara'),
  ('local', 14, 'mahalliy, joydagi', 'We always buy vegetables from the local market.', 'mahalliy'),
  ('magical', 14, 'sehrli, sehr-joduli', 'The castle looked magical under the moonlight.', 'sehrli'),
  ('mail', 14, 'pochta, xat; yubormoq', 'She received a letter in the mail today.', 'pochta'),
  ('novel', 14, 'roman, kitob; yangi', 'She read a famous novel by a Russian author.', 'roman'),
  ('outline', 14, 'reja, sxema; chizib chiqmoq', 'Write an outline before starting your essay.', 'reja'),
  ('poet', 14, 'shoir, badiiy muallif', 'The poet wrote beautiful verses about nature.', 'shoir'),
  ('print', 14, 'chop etmoq, bosmoq', 'Please print two copies of this document.', 'chop etmoq'),
  ('scene', 14, 'sahna, manzara; joy', 'The crime scene was carefully examined by police.', 'sahna'),
  ('sheet', 14, 'varaq, choyshab; qatlam', 'Write your name on the top of the sheet.', 'varaq'),
  ('silly', 14, 'ahmoqona, bema''ni', 'Do not make silly mistakes in your exam.', 'ahmoqona'),
  ('store', 14, 'do''kon; saqlamoq', 'She stores her documents in a safe place.', 'do''kon; saqlamoq'),
  ('suffer', 14, 'azob chekmoq, og''riq sezmoq', 'He suffered from a serious illness for months.', 'azob chekmoq'),
  ('technology', 14, 'texnologiya, fan va texnika', 'Technology has changed the way we communicate.', 'texnologiya'),
  ('across', 15, 'narigi tomonda, kesib o''tib', 'The school is just across the street.', 'narigi tomonda'),
  ('breathe', 15, 'nafas olmoq, nafas chiqarmoq', 'Take a deep breath and breathe out slowly.', 'nafas olmoq'),
  ('characteristic', 15, 'xususiyat, belgi; xos', 'Honesty is a great characteristic to have.', 'xususiyat'),
  ('consume', 15, 'iste''mol qilmoq, sarflamoq', 'People consume a lot of plastic every year.', 'iste''mol qilmoq'),
  ('excite', 15, 'qo''zg''atmoq, hayajonga solmoq', 'The news of the trip excited all the students.', 'qo''zg''atmoq'),
  ('extreme', 15, 'ekstremal, haddan tashqari', 'The athletes trained in extreme weather conditions.', 'ekstremal'),
  ('fear', 15, 'qo''rquv, xavotir; qo''rqmoq', 'She had a strong fear of speaking in public.', 'qo''rquv'),
  ('fortunate', 15, 'omadli, baxtli', 'He was fortunate to find a good job quickly.', 'omadli'),
  ('happen', 15, 'sodir bo''lmoq, yuz bermoq', 'What happened at school today?', 'sodir bo''lmoq'),
  ('length', 15, 'uzunlik, davomiyligi', 'What is the length of this table?', 'uzunlik'),
  ('mistake', 15, 'xato, yanglishish', 'Everyone makes mistakes when learning something new.', 'xato'),
  ('observe', 15, 'kuzatmoq, nazorat qilmoq', 'Scientists observe the stars through a telescope.', 'kuzatmoq'),
  ('opportunity', 15, 'imkoniyat, fursat', 'Travel gives you the opportunity to learn new cultures.', 'imkoniyat'),
  ('prize', 15, 'mukofot, sovrin; qadrlamoq', 'She won the first prize in the art competition.', 'mukofot'),
  ('race', 15, 'irq; musobaqa; yugurish', 'He won the race with the fastest time.', 'irq; musobaqa; yugurish'),
  ('realize', 15, 'anglamoq, tushunmoq', 'She realized she had forgotten her homework.', 'anglamoq'),
  ('respond', 15, 'javob bermoq, munosabat bildirmoq', 'Please respond to the email as soon as possible.', 'javob bermoq'),
  ('risk', 15, 'xavf, xatar; xavf ostiga qo''ymoq', 'Driving too fast is a risk to everyone on the road.', 'xavf'),
  ('wonder', 15, 'ajablanmoq; mo''jiza', 'I wonder what the weather will be like tomorrow.', 'ajablanmoq; mo''jiza'),
  ('yet', 15, 'hali, lekin; allaqachon', 'She has not finished her homework yet.', 'hali'),
  ('academy', 16, 'akademiya, o''quv muassasasi', 'She studied at a music academy for five years.', 'akademiya'),
  ('ancient', 16, 'qadimiy, azaliy', 'Rome is famous for its ancient buildings.', 'qadimiy'),
  ('board', 16, 'taxtacha; kengash; minmoq', 'Write your answers on the board, please.', 'taxtacha; kengash; minmoq'),
  ('century', 16, 'asr, yuz yil', 'The building was built in the nineteenth century.', 'asr'),
  ('clue', 16, 'iz, dalil; yechim', 'The detective found an important clue at the scene.', 'iz'),
  ('concert', 16, 'konsert, musiqa kechasi', 'We attended a classical music concert last night.', 'konsert'),
  ('county', 16, 'tuman, viloyat (inglizda)', 'She works in the county government office.', 'tuman'),
  ('dictionary', 16, 'lug''at, so''zlik', 'Look up the word in the dictionary.', 'lug''at'),
  ('exist', 16, 'mavjud bo''lmoq, yashash', 'Do you believe that ghosts exist?', 'mavjud bo''lmoq'),
  ('flat', 16, 'tekis, yassi; kvartira', 'She lives in a small flat near the city center.', 'tekis'),
  ('gentleman', 16, 'janob, mulozamat bilan tutuvchi erkak', 'He was a true gentleman who helped everyone.', 'janob'),
  ('hidden', 16, 'yashirilgan, maxfiy', 'The treasure was hidden under a large rock.', 'yashirilgan'),
  ('maybe', 16, 'balki, ehtimol', 'Maybe we can go to the park this afternoon.', 'balki'),
  ('officer', 16, 'ofitser; xodim, mansabdor shaxs', 'The police officer helped the lost child.', 'ofitser; xodim'),
  ('original', 16, 'asl, original; dastlabki', 'This painting is an original work of art.', 'asl'),
  ('pound', 16, 'funt; urib maydalash', 'She bought one pound of flour at the market.', 'funt; urib maydalash'),
  ('process', 16, 'jarayon, bosqich; qayta ishlash', 'Learning a language is a long process.', 'jarayon'),
  ('publish', 16, 'nashr etmoq, chop qilmoq', 'She published her first book at age twenty-five.', 'nashr etmoq'),
  ('theater', 16, 'teatr, kino; operatsiya xonasi', 'We watched a play at the local theater.', 'teatr'),
  ('wealth', 16, 'boylik, mol-mulk', 'Health is more important than wealth.', 'boylik'),
  ('appreciate', 17, 'qadrlash, minnatdorchilik bildirmoq', 'I really appreciate your help today.', 'qadrlash'),
  ('available', 17, 'mavjud, bo''sh, olish mumkin', 'Is the manager available for a meeting now?', 'mavjud'),
  ('beat', 17, 'urmoq, mag''lub etmoq; ritm', 'Our team beat the other team five to two.', 'urmoq'),
  ('bright', 17, 'yorqin, aqlli; ravshan', 'She is a bright student with great potential.', 'yorqin'),
  ('celebrate', 17, 'nishonlamoq, bayram qilmoq', 'We celebrated her birthday with a big cake.', 'nishonlamoq'),
  ('determine', 17, 'aniqlash, hal qilmoq', 'Scientists try to determine the age of fossils.', 'aniqlash'),
  ('disappear', 17, 'yo''qolmoq, g''oyib bo''lmoq', 'The magician made the rabbit disappear.', 'yo''qolmoq'),
  ('else', 17, 'boshqa, yana; aks holda', 'Is there anything else I can help you with?', 'boshqa'),
  ('fair', 17, 'adolatli, to''g''ri; ko''rgazma', 'The teacher gave everyone a fair chance to speak.', 'adolatli'),
  ('flow', 17, 'oqmoq, oqish; ravon bo''lmoq', 'The river flows slowly through the valley.', 'oqmoq'),
  ('forward', 17, 'oldinga, kelajakka', 'Please move forward and find a seat at the front.', 'oldinga'),
  ('hill', 17, 'tepalik, do''nglik', 'She climbed the hill to enjoy the view.', 'tepalik'),
  ('level', 17, 'daraja, sath; tekis', 'What level is your English course?', 'daraja'),
  ('lone', 17, 'yolg''iz, bitta', 'A lone traveler walked along the empty road.', 'yolg''iz'),
  ('puddle', 17, 'ko''lmak, suv to''planishi', 'Children love jumping in puddles after rain.', 'ko''lmak'),
  ('response', 17, 'javob, munosabat', 'We are waiting for a response to our email.', 'javob'),
  ('season', 17, 'fasl, mavsim', 'Spring is my favorite season of the year.', 'fasl'),
  ('solution', 17, 'yechim, echim; eritma', 'We need to find a solution to this problem.', 'yechim'),
  ('waste', 17, 'isrof qilmoq, chiqindi', 'Do not waste water, it is very precious.', 'isrof qilmoq'),
  ('whether', 17, 'yo yoki; yoki-yoki', 'I am not sure whether she will come today.', 'yo yoki; yoki-yoki'),
  ('argue', 18, 'bahslashmoq, tortishmoq', 'They argued about which film to watch.', 'bahslashmoq'),
  ('communicate', 18, 'muloqot qilmoq, aloqa o''rnatmoq', 'It is important to communicate clearly at work.', 'muloqot qilmoq'),
  ('crowd', 18, 'olomon, to''da; to''planmoq', 'A large crowd gathered to watch the concert.', 'olomon'),
  ('depend', 18, 'bog''liq bo''lmoq, ishonmoq', 'Your results depend on how hard you study.', 'bog''liq bo''lmoq'),
  ('dish', 18, 'idish; taom', 'She cooked a delicious dish for the dinner party.', 'idish; taom'),
  ('empty', 18, 'bo''sh, hech narsa yo''q; bo''shatmoq', 'The classroom was empty when I arrived.', 'bo''sh'),
  ('exact', 18, 'aniq, to''g''ri; aynan', 'I do not remember the exact time of the meeting.', 'aniq'),
  ('fresh', 18, 'yangi, toza', 'Fresh vegetables are better than canned ones.', 'yangi'),
  ('gather', 18, 'yig''ilmoq, to''planmoq', 'The family gathers every Sunday for dinner.', 'yig''ilmoq'),
  ('indicate', 18, 'ko''rsatmoq, bildirmoq', 'The sign indicates that parking is not allowed here.', 'ko''rsatmoq'),
  ('item', 18, 'narsa, mahsulot; modda', 'Please check every item on the list.', 'narsa'),
  ('offer', 18, 'taklif qilmoq, bermoq; taklif', 'He offered to help carry the heavy bags.', 'taklif qilmoq'),
  ('price', 18, 'narx, qiymat', 'The price of food has increased this year.', 'narx'),
  ('product', 18, 'mahsulot, tovar', 'This company makes high-quality dairy products.', 'mahsulot'),
  ('property', 18, 'mulk, yer; xususiyat', 'She owns a property in the north of the city.', 'mulk'),
  ('purchase', 18, 'sotib olmoq; xarid', 'She purchased a new laptop for her studies.', 'sotib olmoq; xarid'),
  ('recommend', 18, 'tavsiya qilmoq, maslahat bermoq', 'I recommend this restaurant for a special dinner.', 'tavsiya qilmoq'),
  ('select', 18, 'tanlash, ajratib olmoq', 'Select the correct answer from the options below.', 'tanlash'),
  ('tool', 18, 'asbob, qurol; vosita', 'A hammer is a common tool used in construction.', 'asbob'),
  ('treat', 18, 'muomala qilmoq; davolash; siylash', 'Treat others the way you want to be treated.', 'muomala qilmoq; davolash; siylash'),
  ('alive', 19, 'tirik, hayot; faol', 'Luckily, all the passengers survived and were alive.', 'tirik'),
  ('bone', 19, 'suyak', 'She broke a bone in her arm while playing sport.', 'suyak'),
  ('bother', 19, 'bezovta qilmoq, tashvishga solmoq', 'I am sorry to bother you, but I need help.', 'bezovta qilmoq'),
  ('captain', 19, 'kapitan, rahbar', 'The captain of the ship gave orders to the crew.', 'kapitan'),
  ('conclusion', 19, 'xulosa, yakun', 'The conclusion of the essay must be clear.', 'xulosa'),
  ('doubt', 19, 'shubha, gumon; shubhalanmoq', 'I have no doubt that she will succeed.', 'shubha'),
  ('explore', 19, 'o''rganmoq, kashf etmoq', 'Scientists explore the ocean floor for new species.', 'o''rganmoq'),
  ('foreign', 19, 'xorijiy, chet el', 'She is studying a foreign language at university.', 'xorijiy'),
  ('glad', 19, 'xursand, mamnun', 'I am glad to hear that you passed the exam.', 'xursand'),
  ('however', 19, 'lekin, biroq; shunga qaramay', 'He studied hard; however, he failed the test.', 'lekin'),
  ('injustice', 19, 'adolatsizlik, huquq buzilishi', 'She fought against injustice in her community.', 'adolatsizlik'),
  ('international', 19, 'xalqaro, davlatlararo', 'She works for an international organization.', 'xalqaro'),
  ('lawyer', 19, 'advokat, yurist', 'She hired a lawyer to help with her case.', 'advokat'),
  ('mention', 19, 'eslatmoq, aytib o''tmoq', 'He mentioned that he would be late for class.', 'eslatmoq'),
  ('policy', 19, 'siyosat, qoida; yo''riqnoma', 'The school has a strict policy on mobile phones.', 'siyosat'),
  ('social', 19, 'ijtimoiy, jamoatchilik', 'She has strong social skills and many friends.', 'ijtimoiy'),
  ('speech', 19, 'nutq, so''zlash; rech', 'She gave a powerful speech at the graduation ceremony.', 'nutq'),
  ('staff', 19, 'xodimlar, hodimlar', 'The hotel staff was very helpful during our stay.', 'xodimlar'),
  ('toward', 19, 'tomon, yo''nalishida', 'She walked toward the exit of the building.', 'tomon'),
  ('wood', 19, 'yog''och, o''rmon; daraxt', 'The house was built with wood from a local forest.', 'yog''och'),
  ('achieve', 20, 'erishmoq, amalga oshirmoq', 'She achieved her goal of becoming a doctor.', 'erishmoq'),
  ('advise', 20, 'maslahat bermoq, o''gitlamoq', 'He advised me to study harder for the next exam.', 'maslahat bermoq'),
  ('already', 20, 'allaqachon, endi', 'She has already finished her homework.', 'allaqachon'),
  ('basic', 20, 'asosiy, boshlang''ich', 'You need a basic knowledge of English.', 'asosiy'),
  ('bit', 20, 'bir oz, bo''lak; bir parcha', 'She felt a bit nervous before the presentation.', 'bir oz'),
  ('consider', 20, 'ko''rib chiqmoq, hisobga olmoq', 'Please consider all the options before deciding.', 'ko''rib chiqmoq'),
  ('destroy', 20, 'yo''q qilmoq, buzmoq', 'The fire destroyed several houses in the village.', 'yo''q qilmoq'),
  ('entertain', 20, 'ko''ngil ocharmoq, quvontirmoq', 'The clown entertained the children at the party.', 'ko''ngil ocharmoq'),
  ('extra', 20, 'qo''shimcha, ortiqcha', 'She always brings extra pens to the exam.', 'qo''shimcha'),
  ('goal', 20, 'maqsad, niyat; gol', 'His goal is to become a professional footballer.', 'maqsad'),
  ('lie', 20, 'yolg''on gapirmoq; yotmoq', 'Do not lie about your age on the application.', 'yolg''on gapirmoq; yotmoq'),
  ('meat', 20, 'go''sht, et', 'She does not eat meat because she is vegetarian.', 'go''sht'),
  ('opinion', 20, 'fikr, mulohaza', 'In my opinion, reading is the best way to learn.', 'fikr'),
  ('real', 20, 'haqiqiy, asl, chin', 'Is that a real diamond in her ring?', 'haqiqiy'),
  ('reflect', 20, 'aks ettirmoq; o''ylamoq', 'The lake reflects the mountains in the distance.', 'aks ettirmoq; o''ylamoq'),
  ('regard', 20, 'hisoblamoq; nazar; salom', 'He is regarded as one of the best students.', 'hisoblamoq; nazar; salom'),
  ('serve', 20, 'xizmat qilmoq; uzatmoq', 'The waiter served the food very quickly.', 'xizmat qilmoq; uzatmoq'),
  ('vegetable', 20, 'sabzavot, o''simlik', 'Eat more vegetables to stay healthy.', 'sabzavot'),
  ('war', 20, 'urush, jang', 'The war lasted for many years and caused great suffering.', 'urush'),
  ('worth', 20, 'qimmat, qadrli; arziydigan', 'This book is worth reading more than once.', 'qimmat'),
  ('appear', 21, 'ko''rinmoq, paydo bo''lmoq', 'Stars appear in the sky after sunset.', 'ko''rinmoq'),
  ('base', 21, 'asos, tub; joylashmoq', 'The base of the triangle must be measured.', 'asos'),
  ('brain', 21, 'miya, ong; aql', 'Regular exercise is good for the brain.', 'miya'),
  ('career', 21, 'kasb, martaba, faoliyat', 'She built a successful career in medicine.', 'kasb'),
  ('clerk', 21, 'kotib, menejer; do''kon xodimi', 'The clerk helped the customer find the right size.', 'kotib'),
  ('effort', 21, 'harakat, kuch sarflash', 'She put a lot of effort into her final project.', 'harakat'),
  ('enter', 21, 'kirmoq, qatnashmoq', 'Please knock before you enter the room.', 'kirmoq'),
  ('excellent', 21, 'a''lo, zo''r, mukammal', 'She received excellent marks in all her subjects.', 'a''lo'),
  ('hero', 21, 'qahramon, bahodir', 'The firefighter was called a hero for saving lives.', 'qahramon'),
  ('hurry', 21, 'shoshmoq, tezlashmoq; shoshilinch', 'We need to hurry or we will miss the bus.', 'shoshmoq'),
  ('inform', 21, 'xabar bermoq, ma''lum qilmoq', 'Please inform me when the results are ready.', 'xabar bermoq'),
  ('later', 21, 'keyinroq, undan keyin', 'I will call you later this evening.', 'keyinroq'),
  ('leave', 21, 'ketmoq; tark etmoq; ruxsat', 'She left home early to avoid the traffic.', 'ketmoq; tark etmoq; ruxsat'),
  ('locate', 21, 'joylashuv aniqlash, topmoq', 'Can you locate the city on this map?', 'joylashuv aniqlash'),
  ('nurse', 21, 'hamshira; parvarish qilmoq', 'The nurse took care of the patient all night.', 'hamshira; parvarish qilmoq'),
  ('operation', 21, 'operatsiya, amal; harakat', 'The doctor performed a three-hour operation.', 'operatsiya'),
  ('pain', 21, 'og''riq, azob; dard', 'She felt a sharp pain in her back.', 'og''riq'),
  ('refuse', 21, 'rad etmoq, inkor qilmoq', 'He refused to answer the question in class.', 'rad etmoq'),
  ('though', 21, 'garchi, biroq, lekin', 'Though it was raining, we continued our walk.', 'garchi'),
  ('various', 21, 'turli, har xil', 'The shop sells various types of fruit.', 'turli'),
  ('actual', 22, 'haqiqiy, aslida', 'The actual cost of the trip was more than expected.', 'haqiqiy'),
  ('amaze', 22, 'hayratga solmoq, lol qoldirmoq', 'Her performance amazed everyone in the audience.', 'hayratga solmoq'),
  ('charge', 22, 'to''lov, narx; zaryadlamoq; yuklash', 'There is no charge for children under five.', 'to''lov'),
  ('comfort', 22, 'qulaylik, tasalli; tasalli bermoq', 'A warm cup of tea brings great comfort.', 'qulaylik'),
  ('contact', 22, 'aloqa, muloqot; bog''lanmoq', 'Please contact us if you have any questions.', 'aloqa'),
  ('customer', 22, 'mijoz, xaridor', 'The store always tries to satisfy its customers.', 'mijoz'),
  ('deliver', 22, 'yetkazib bermoq, topshirmoq', 'The postman delivered a package this morning.', 'yetkazib bermoq'),
  ('earn', 22, 'topmoq, ishlab olmoq', 'She earns a good salary as a software engineer.', 'topmoq'),
  ('gate', 22, 'darvoza, eshik; yo''lak', 'Please wait at the gate before boarding the plane.', 'darvoza'),
  ('include', 22, 'o''z ichiga olmoq, qo''shmoq', 'The price includes breakfast and dinner.', 'o''z ichiga olmoq'),
  ('manage', 22, 'boshqarmoq, uddalash', 'She managed to finish the report before the deadline.', 'boshqarmoq'),
  ('mystery', 22, 'sir, jumboq, sirliq', 'The mystery of the missing keys was never solved.', 'sir'),
  ('occur', 22, 'sodir bo''lmoq, yuz bermoq', 'Earthquakes often occur along fault lines.', 'sodir bo''lmoq'),
  ('opposite', 22, 'qarama-qarshi, teskari', 'The bank is on the opposite side of the street.', 'qarama-qarshi'),
  ('plate', 22, 'likop, tarelka; qatlam', 'She put a plate of fruit on the table.', 'likop'),
  ('receive', 22, 'olmoq, qabul qilmoq', 'She received a letter from her university today.', 'olmoq'),
  ('reward', 22, 'mukofot, taqdirlamoq', 'Hard work always brings its own reward.', 'mukofot'),
  ('set', 22, 'o''rnatmoq; to''plam; botmoq', 'She set the alarm for six in the morning.', 'o''rnatmoq; to''plam; botmoq'),
  ('steal', 22, 'o''g''irlamoq, urchmoq', 'Someone stole his wallet on the bus.', 'o''g''irlamoq'),
  ('thief', 22, 'o''g''ri, qaroqchi', 'The thief was caught by the police at the market.', 'o''g''ri'),
  ('advance', 23, 'ilgarilamoq, rivojlanmoq; oldindan', 'Technology continues to advance every year.', 'ilgarilamoq'),
  ('athlete', 23, 'sportchi, atlet', 'She is a talented athlete who trains every day.', 'sportchi'),
  ('average', 23, 'o''rtacha, oddiy; o''rtacha hisob', 'The average temperature in summer is 35 degrees.', 'o''rtacha'),
  ('behavior', 23, 'xulq-atvor, harakat', 'Good behavior is expected from all students.', 'xulq-atvor'),
  ('behind', 23, 'orqada, keyin; sabab sifatida', 'She sat behind the tallest student in class.', 'orqada'),
  ('course', 23, 'kurs, dars; yo''nalish; tabiiy ravishda', 'She enrolled in an English course last month.', 'kurs'),
  ('lower', 23, 'pastroq, kamroq; tushirmoq', 'Please lower your voice in the library.', 'pastroq'),
  ('match', 23, 'mos kelmoq; musobaqa; gugurt', 'The colors of your shoes match your jacket.', 'mos kelmoq; musobaqa; gugurt'),
  ('member', 23, 'a''zo, ishtirokchi', 'She became a member of the school choir.', 'a''zo'),
  ('mental', 23, 'aqliy, psixologik', 'Regular rest is important for good mental health.', 'aqliy'),
  ('passenger', 23, 'yo''lovchi, musofir', 'All passengers must fasten their seatbelts.', 'yo''lovchi'),
  ('personality', 23, 'shaxsiyat, xarakter', 'She has a warm and friendly personality.', 'shaxsiyat'),
  ('poem', 23, 'she''r, nazmiy asar', 'He wrote a beautiful poem about the mountains.', 'she''r'),
  ('pole', 23, 'ustun, qutb; tayoq', 'The flag was tied to a tall metal pole.', 'ustun'),
  ('remove', 23, 'olib tashlamoq, yo''qotmoq', 'Please remove your shoes before entering.', 'olib tashlamoq'),
  ('safety', 23, 'xavfsizlik, omon-esen', 'Always wear a helmet for safety when cycling.', 'xavfsizlik'),
  ('shoot', 23, 'otmoq, rasga olmoq', 'The photographer shot amazing photos in the forest.', 'otmoq'),
  ('sound', 23, 'tovush, ovoz; sog''lom; eshitilmoq', 'The sound of the rain helped her fall asleep.', 'tovush'),
  ('swim', 23, 'suzmoq, cho''milmoq', 'She swims in the pool every morning.', 'suzmoq'),
  ('web', 23, 'to''r, o''rgimchak to''ri; internet', 'The spider built a delicate web in the corner.', 'to''r'),
  ('block', 24, 'to''siq, blok; to''sib qo''ymoq', 'A fallen tree blocked the road completely.', 'to''siq'),
  ('cheer', 24, 'mamnunlik; rag''batlantirmoq; xursandlik', 'The crowd cheered loudly when the team scored.', 'mamnunlik; rag''batlantirmoq; xursandlik'),
  ('complex', 24, 'murakkab, qiyin; majmua', 'The math problem was too complex for beginners.', 'murakkab'),
  ('critic', 24, 'tanqidchi, munaqqid', 'The film received mixed reviews from critics.', 'tanqidchi'),
  ('event', 24, 'tadbir, voqea; hodisa', 'The school held a cultural event last Friday.', 'tadbir'),
  ('exercise', 24, 'mashq, jismoniy tarbiya; bajarmoq', 'Daily exercise helps improve your health.', 'mashq'),
  ('fit', 24, 'mos kelmoq; sog''lom; sig''moq', 'The new dress fits her perfectly.', 'mos kelmoq; sog''lom; sig''moq'),
  ('friendship', 24, 'do''stlik, birodarlik', 'Their friendship lasted for more than thirty years.', 'do''stlik'),
  ('guide', 24, 'yo''lboshchi; qo''llanma; boshqarmoq', 'The guide led us through the old part of the city.', 'yo''lboshchi; qo''llanma; boshqarmoq'),
  ('lack', 24, 'yetishmovchilik, kamchilik', 'A lack of sleep affects your concentration.', 'yetishmovchilik'),
  ('passage', 24, 'o''tish, yo''lak; matn', 'Read the passage and answer the questions below.', 'o''tish'),
  ('perform', 24, 'ijro etmoq, ko''rsatmoq', 'She performed a beautiful dance at the ceremony.', 'ijro etmoq'),
  ('pressure', 24, 'bosim, tazyiq; bosmoq', 'He worked well under pressure and met the deadline.', 'bosim'),
  ('probable', 24, 'ehtimoliy, kutilayotgan', 'Rain is probable in the evening.', 'ehtimoliy'),
  ('public', 24, 'ommaviy, jamoat; jamiyat', 'She spoke in public for the first time at school.', 'ommaviy'),
  ('strike', 24, 'zarba; ish tashlash; urmoq', 'The workers decided to go on strike for better pay.', 'zarba; ish tashlash; urmoq'),
  ('support', 24, 'qo''llab-quvvatlamoq; tayanch', 'Her family always supports her decisions.', 'qo''llab-quvvatlamoq; tayanch'),
  ('task', 24, 'vazifa, topshiriq', 'Complete all the tasks before the end of the class.', 'vazifa'),
  ('term', 24, 'atama; muddat; semestr', 'The school term starts in September every year.', 'atama; muddat; semestr'),
  ('unite', 24, 'birlashmoq, birlashtirmoq', 'The two teams united to win the championship.', 'birlashmoq'),
  ('associate', 25, 'bog''lash, qo''shmoq; hamkasb', 'People often associate the color red with danger.', 'bog''lash'),
  ('environment', 25, 'atrof-muhit, muhit', 'We must protect the environment for future generations.', 'atrof-muhit'),
  ('factory', 25, 'zavod, fabrika', 'The factory produces over a thousand cars every day.', 'zavod'),
  ('feature', 25, 'xususiyat; belgi; ko''rsatmoq', 'One great feature of this phone is its camera.', 'xususiyat; belgi; ko''rsatmoq'),
  ('instance', 25, 'misol, holat; masalan', 'For instance, she speaks three foreign languages.', 'misol'),
  ('involve', 25, 'o''z ichiga olmoq, jalb etmoq', 'The project involves a lot of research and planning.', 'o''z ichiga olmoq'),
  ('medicine', 25, 'dori, dorivor; tibbiyot', 'Take this medicine twice a day after meals.', 'dori'),
  ('mix', 25, 'aralashmoq, qo''shmoq; aralashma', 'Mix the flour and sugar together in a bowl.', 'aralashmoq'),
  ('organize', 25, 'tashkil etmoq, tartiblashtirmoq', 'She organized a surprise party for her friend.', 'tashkil etmoq'),
  ('period', 25, 'davr, muddat; nuqta', 'She studied art during the Renaissance period.', 'davr'),
  ('populate', 25, 'aholi bilan to''ldirmoq, yashamoq', 'The region is densely populated.', 'aholi bilan to''ldirmoq'),
  ('produce', 25, 'ishlab chiqarmoq, yaratmoq; mahsulot', 'This farm produces organic vegetables.', 'ishlab chiqarmoq'),
  ('range', 25, 'oraliq, ko''lam; keng qamrov', 'The shop sells a wide range of products.', 'oraliq'),
  ('recognize', 25, 'tanish, aniqlash; tan olmoq', 'I recognized her voice on the phone immediately.', 'tanish'),
  ('regular', 25, 'muntazam, doimiy; oddiy', 'Regular practice is the key to improvement.', 'muntazam'),
  ('sign', 25, 'belgi, imo; imzo; imzolamoq', 'She made a sign that said Welcome for the party.', 'belgi'),
  ('tip', 25, 'maslahat; uchi; choy puli', 'Her teacher gave her useful tips for the exam.', 'maslahat; uchi; choy puli'),
  ('tradition', 25, 'an''ana, urf-odat', 'It is a tradition to give gifts on birthdays.', 'an''ana'),
  ('trash', 25, 'axlat, chiqit; chiqit qilmoq', 'Please put the trash in the bin outside.', 'axlat'),
  ('wide', 25, 'keng, katta; bir tomondan boshqasigacha', 'The river is very wide at this point.', 'keng'),
  ('advice', 26, 'maslahat, tavsiya', 'She gave me useful advice about studying English.', 'maslahat'),
  ('along', 26, 'bo''ylab, birga', 'They walked along the river in the evening.', 'bo''ylab'),
  ('attention', 26, 'e''tibor, diqqat', 'Please pay attention to the teacher''s explanation.', 'e''tibor'),
  ('attract', 26, 'jalb etmoq, qiziqtirmoq', 'The colorful display attracted many customers.', 'jalb etmoq'),
  ('climb', 26, 'chiqmoq, tirmoashmoq', 'She climbed to the top of the tall ladder.', 'chiqmoq'),
  ('drop', 26, 'tushirmoq, tomchilamoq; pasaymoq', 'She dropped her pen on the floor.', 'tushirmoq'),
  ('final', 26, 'yakuniy, oxirgi; final', 'The final exam will be held next Friday.', 'yakuniy'),
  ('further', 26, 'bundan tashqari; uzoqroq', 'Can you explain this idea further, please?', 'bundan tashqari; uzoqroq'),
  ('imply', 26, 'nazarda tutmoq, anglatmoq', 'Her silence implied that she was unhappy.', 'nazarda tutmoq'),
  ('maintain', 26, 'saqlash, ushlab turmoq', 'It is important to maintain a healthy lifestyle.', 'saqlash'),
  ('neither', 26, 'na biri, na boshqasi; ham emas', 'Neither of the answers was correct.', 'na biri'),
  ('otherwise', 26, 'aks holda, boshqacha', 'Study hard; otherwise, you will fail the exam.', 'aks holda'),
  ('physical', 26, 'jismoniy, fizikaviy', 'Regular physical activity improves your health.', 'jismoniy'),
  ('prove', 26, 'isbotlamoq, ko''rsatmoq', 'She proved that hard work leads to success.', 'isbotlamoq'),
  ('react', 26, 'munosabat bildirmoq, javob bermoq', 'How did she react when she heard the news?', 'munosabat bildirmoq'),
  ('ride', 26, 'minmoq, yurishmoq; sayohat', 'She rides her bike to school every morning.', 'minmoq'),
  ('situated', 26, 'joylashgan, turgan', 'The hotel is situated near the city center.', 'joylashgan'),
  ('society', 26, 'jamiyat, ijtimoiy hayot', 'Education plays a key role in a healthy society.', 'jamiyat'),
  ('standard', 26, 'standart, me''yor; darajasi', 'The school has very high academic standards.', 'standart'),
  ('suggest', 26, 'taklif etmoq, maslahat bermoq', 'She suggested meeting at the library to study.', 'taklif etmoq'),
  ('actually', 27, 'aslida, haqiqatda', 'I actually enjoyed the difficult exam.', 'aslida'),
  ('bite', 27, 'tishlamoq, chaqqan; tishlay', 'The dog bit the postman on the leg.', 'tishlamoq'),
  ('coast', 27, 'qirg''oq, sohill', 'They drove along the coast and enjoyed the view.', 'qirg''oq'),
  ('deal', 27, 'kelishuv, bitim; muomala qilmoq', 'They made a deal to share the work equally.', 'kelishuv'),
  ('desert', 27, 'cho''l, sahro; tark etmoq', 'The camel is well adapted to life in the desert.', 'cho''l'),
  ('earthquake', 27, 'zilzila, yer silkinishi', 'The earthquake damaged many buildings in the city.', 'zilzila'),
  ('effective', 27, 'samarali, natijali', 'She uses an effective method to learn vocabulary.', 'samarali'),
  ('examine', 27, 'ko''rib chiqmoq, tekshirmoq', 'The doctor examined the patient carefully.', 'ko''rib chiqmoq'),
  ('false', 27, 'yolg''on, noto''g''ri', 'The news report turned out to be completely false.', 'yolg''on'),
  ('gift', 27, 'sovg''a; iste''dod', 'She gave her mother a beautiful gift for her birthday.', 'sovg''a; iste''dod'),
  ('hunger', 27, 'och qolish, ishtaha; chanqoqlik', 'World hunger is a major global problem.', 'och qolish'),
  ('imagine', 27, 'tasavvur qilmoq, ko''z oldiga keltirmoq', 'Imagine living on another planet in the future.', 'tasavvur qilmoq'),
  ('journey', 27, 'safar, sayohat', 'The journey from Tashkent to Samarkand takes three hours.', 'safar'),
  ('puzzle', 27, 'jumboq, topishmoq; sarosimaga tushirmoq', 'She enjoys solving crossword puzzles.', 'jumboq'),
  ('quite', 27, 'ancha, juda; bir oz', 'The test was quite difficult for most students.', 'ancha'),
  ('rather', 27, 'aksincha, biroz; nisbatan', 'She would rather read than watch television.', 'aksincha'),
  ('specific', 27, 'aniq, muayyan; maxsus', 'Please give a specific example to support your answer.', 'aniq'),
  ('tour', 27, 'sayohat, tur; gastrol', 'They went on a guided tour of the old city.', 'sayohat'),
  ('trip', 27, 'sayohat, safarcha; qoqilish', 'Our class went on a trip to the science museum.', 'sayohat'),
  ('value', 27, 'qiymat, qadr; qadrlash', 'Education has a high value in our culture.', 'qiymat'),
  ('band', 28, 'guruh, to''da; lenta; birikmoq', 'Her favorite band is performing live tonight.', 'guruh'),
  ('barely', 28, 'zo''rg''a, qiyinchilik bilan', 'She barely had enough time to finish the exam.', 'zo''rg''a'),
  ('boring', 28, 'zeriktiradigan, qiziqarsiz', 'The lecture was so boring that he fell asleep.', 'zeriktiradigan'),
  ('cancel', 28, 'bekor qilmoq, rad etmoq', 'The flight was cancelled due to bad weather.', 'bekor qilmoq'),
  ('driveway', 28, 'yo''lakcha, avtomobil yo''li', 'She parked her car in the driveway.', 'yo''lakcha'),
  ('garbage', 28, 'axlat, chiqit', 'Please take out the garbage before you leave.', 'axlat'),
  ('instrument', 28, 'musiqa asbobi; asbob; qurol', 'She plays the piano and one other instrument.', 'musiqa asbobi; asbob; qurol'),
  ('list', 28, 'ro''yxat; ro''yxatga kiritmoq', 'Write a list of the vocabulary words you know.', 'ro''yxat; ro''yxatga kiritmoq'),
  ('magic', 28, 'sehrgari; sehr; mo''jizakor', 'The magician performed amazing magic tricks.', 'sehrgari; sehr; mo''jizakor'),
  ('message', 28, 'xabar, habar; mazmun', 'She left a message on my phone last night.', 'xabar'),
  ('notice', 28, 'e''tibor bermoq, payqamoq; e''lon', 'Did you notice the new sign on the door?', 'e''tibor bermoq'),
  ('own', 28, 'o''ziga tegishli; egalik qilmoq', 'She owns a small bakery in the old part of town.', 'o''ziga tegishli; egalik qilmoq'),
  ('predict', 28, 'bashorat qilmoq, oldindan aytmoq', 'Scientists try to predict future climate changes.', 'bashorat qilmoq'),
  ('professor', 28, 'professor, o''qituvchi', 'The professor explained the theory clearly.', 'professor'),
  ('rush', 28, 'shoshmoq, yugurmoq; to''lqin', 'There is no need to rush; we have enough time.', 'shoshmoq'),
  ('schedule', 28, 'jadval, reja; rejalashtirilgan', 'She checked her schedule before the meeting.', 'jadval'),
  ('share', 28, 'ulashmoq, bo''lishmoq; ulush', 'Please share your ideas with the rest of the class.', 'ulashmoq'),
  ('stage', 28, 'sahna; bosqich; darajasi', 'The final stage of the project was the hardest.', 'sahna; bosqich; darajasi'),
  ('storm', 28, 'bo''ron, dovul; hujum', 'The storm knocked down many trees in the park.', 'bo''ron'),
  ('within', 28, 'ichida, vaqt ichida; doirasida', 'Please complete the task within thirty minutes.', 'ichida'),
  ('advertise', 29, 'reklama qilmoq, e''lon bermoq', 'They advertised the new product on television.', 'reklama qilmoq'),
  ('assign', 29, 'topshirmoq, belgilamoq', 'The teacher assigned a reading task for homework.', 'topshirmoq'),
  ('audience', 29, 'auditoriya, tomoshabin; tinglovchi', 'The audience clapped loudly after the performance.', 'auditoriya'),
  ('breakfast', 29, 'nonushta, ertalabki ovqat', 'She always has a healthy breakfast before school.', 'nonushta'),
  ('competition', 29, 'musobaqa, tanlov; raqobat', 'She won first place in the national writing competition.', 'musobaqa'),
  ('cool', 29, 'salqin; zo''r, ajoyib; sovitmoq', 'It is cool to wear a jacket in the evening.', 'salqin; zo''r'),
  ('gain', 29, 'olmoq, qozonmoq; foyda', 'She gained a lot of knowledge from traveling.', 'olmoq'),
  ('importance', 29, 'muhimlik, ahamiyat', 'She spoke about the importance of daily exercise.', 'muhimlik'),
  ('knowledge', 29, 'bilim, ma''lumot', 'Reading books is the best way to gain knowledge.', 'bilim'),
  ('major', 29, 'asosiy, katta; mutaxassislik', 'She chose history as her major at university.', 'asosiy'),
  ('mean', 29, 'anglatmoq; o''rtacha; xasis', 'What does this word mean in English?', 'anglatmoq; o''rtacha; xasis'),
  ('prefer', 29, 'afzal ko''rmoq, yoqtirmoq', 'She prefers tea to coffee in the morning.', 'afzal ko''rmoq'),
  ('president', 29, 'prezident, rais', 'She was elected president of the student council.', 'prezident'),
  ('progress', 29, 'rivojlanish, muvaffaqiyat; oldinga bormoq', 'She made great progress in her English lessons.', 'rivojlanish'),
  ('respect', 29, 'hurmat; hurmat qilmoq', 'Always show respect to your teachers and elders.', 'hurmat; hurmat qilmoq'),
  ('rich', 29, 'boy, serob; to''yimli', 'She comes from a rich family but lives simply.', 'boy'),
  ('skill', 29, 'ko''nikma, mahorat', 'Writing is an important skill for university students.', 'ko''nikma'),
  ('somehow', 29, 'qandaydir, bir yo''l bilan', 'She somehow managed to finish everything on time.', 'qandaydir'),
  ('strength', 29, 'kuch, quvvat; qodir bo''lish', 'Hard work and patience are her greatest strengths.', 'kuch'),
  ('vote', 29, 'ovoz bermoq; ovoz; saylov', 'Everyone has the right to vote in an election.', 'ovoz bermoq; ovoz; saylov'),
  ('above', 30, 'ustida, tepasida; yuqorida', 'The temperature rose above forty degrees yesterday.', 'ustida'),
  ('ahead', 30, 'oldinda, kelajakda', 'She is ahead of the other students in English.', 'oldinda'),
  ('amount', 30, 'miqdor, ko''lam; jamlab', 'A small amount of sugar is enough for this recipe.', 'miqdor'),
  ('belief', 30, 'e''tiqod, ishonch; yondashuv', 'Her belief in hard work helped her succeed.', 'e''tiqod'),
  ('center', 30, 'markaz, o''rta; markaziy', 'The shopping center is in the middle of the city.', 'markaz'),
  ('common', 30, 'umumiy, keng tarqalgan; odatiy', 'English is a common language used around the world.', 'umumiy'),
  ('cost', 30, 'narx, xarajat; turmoq', 'The cost of living has increased significantly.', 'narx'),
  ('demonstrate', 30, 'ko''rsatmoq, isbotlamoq', 'She demonstrated how to solve the problem step by step.', 'ko''rsatmoq'),
  ('different', 30, 'farqli, boshqa; turli', 'People learn in many different ways.', 'farqli'),
  ('evidence', 30, 'dalil, isbot; ko''rsatmoq', 'The lawyer presented clear evidence in court.', 'dalil'),
  ('honesty', 30, 'halollik, to''g''rilik', 'Honesty is the most important quality in a friend.', 'halollik'),
  ('idiom', 30, 'idioma, frazeologik birlik', 'She learns one new idiom in English every day.', 'idioma'),
  ('independent', 30, 'mustaqil, o''z-o''zicha', 'She is an independent learner who studies alone.', 'mustaqil'),
  ('inside', 30, 'ichida, ichki qism; kirish', 'Please wait inside until the rain stops.', 'ichida'),
  ('master', 30, 'ustoz, mahoratli; egalamoq', 'It takes years to master a foreign language.', 'ustoz'),
  ('memory', 30, 'xotira, eslab qolish; yodgorlik', 'She has an excellent memory for vocabulary.', 'xotira'),
  ('proper', 30, 'to''g''ri, mos; tegishli', 'Always use proper grammar when writing formally.', 'to''g''ri'),
  ('scan', 30, 'skanerlash; ko''zdan kechirmoq', 'She scanned the document and sent it by email.', 'skanerlash; ko''zdan kechirmoq'),
  ('section', 30, 'bo''lim, qism; kesma', 'Read the first section of the chapter carefully.', 'bo''lim'),
  ('surface', 30, 'yuza, sirt; ustki qism', 'The surface of the table was scratched.', 'yuza');

-- Tekshirish
SELECT day_number, COUNT(*) as count FROM word_entries WHERE day_number BETWEEN 1 AND 30 GROUP BY day_number ORDER BY day_number;
