-- word_entries ga so'zlarni qo'shish - Kunlar 11-20
-- Bu faylni Supabase SQL Editor'da alohida ishga tushiring

INSERT INTO word_entries (word, day_number, meaning, example, synonym) VALUES
  ('anymore', 11, 'endi, boshqa', 'She does not live here anymore.', 'endi'),
  ('asleep', 11, 'uxlab, uyquda', 'The baby fell asleep after drinking milk.', 'uxlab'),
  ('berry', 11, 'rezavor, meva (kichik)', 'She picked fresh berries from the garden.', 'rezavor'),
  ('collect', 11, 'yig''moq, to''plamoq', 'He collects stamps from different countries.', 'yig''moq'),
  ('compete', 11, 'musobaqa qilmoq, raqobatlashmoq', 'Students will compete in the spelling contest.', 'musobaqa qilmoq'),
  ('conversation', 11, 'suhbat, muloqot', 'We had a long conversation about our future plans.', 'suhbat'),
  ('creature', 11, 'jonzot, mavjudot', 'The forest is home to many interesting creatures.', 'jonzot'),
  ('decision', 11, 'qaror, tanlov', 'Making the right decision takes time and thought.', 'qaror'),
  ('either', 11, 'ham, yoki; ikkalasi ham', 'You can choose either tea or coffee.', 'ham'),
  ('forest', 11, 'o''rmon, daraxt', 'The forest was quiet and full of tall trees.', 'o''rmon'),
  ('ground', 11, 'er, zamin; asos', 'The children sat on the ground and ate lunch.', 'er'),
  ('introduce', 11, 'tanishtirmoq, kiritmoq', 'Let me introduce you to my best friend.', 'tanishtirmoq'),
  ('marry', 11, 'turmushga chiqmoq, uylanmoq', 'They will marry in the spring next year.', 'turmushga chiqmoq'),
  ('prepare', 11, 'tayyorlanmoq, tayyorlamoq', 'She prepared carefully for her job interview.', 'tayyorlanmoq'),
  ('sail', 11, 'yelkan; suzib ketmoq', 'The boat sailed across the calm ocean.', 'yelkan; suzib ketmoq'),
  ('serious', 11, 'jiddiy, muhim', 'This is a serious problem that needs attention.', 'jiddiy'),
  ('spend', 11, 'sarflamoq, o''tkazmoq', 'He spends a lot of time reading books.', 'sarflamoq'),
  ('strange', 11, 'g''alati, notanish', 'There was a strange noise coming from outside.', 'g''alati'),
  ('truth', 11, 'haqiqat, to''g''rilik', 'Always tell the truth, even when it is hard.', 'haqiqat'),
  ('wake', 11, 'uyg''onmoq, uyg''otmoq', 'She woke up early to study before school.', 'uyg''onmoq'),
  ('alone', 12, 'yolg''iz, bir o''zi', 'She felt alone in the big city.', 'yolg''iz'),
  ('apartment', 12, 'kvartira, turar joy', 'They moved into a new apartment last month.', 'kvartira'),
  ('article', 12, 'maqola; modda; artikl', 'She wrote an article for the school newspaper.', 'maqola; modda; artikl'),
  ('artist', 12, 'rassom, san''atkor', 'The artist painted a beautiful landscape.', 'rassom'),
  ('attitude', 12, 'munosabat, qarash', 'A positive attitude helps you succeed in life.', 'munosabat'),
  ('compare', 12, 'solishtirmoq, taqqoslamoq', 'Compare these two sentences and find the difference.', 'solishtirmoq'),
  ('judge', 12, 'sudya; hukm chiqarmoq', 'Do not judge people by their appearance.', 'sudya; hukm chiqarmoq'),
  ('magazine', 12, 'jurnal, gazeta', 'She reads a fashion magazine every month.', 'jurnal'),
  ('material', 12, 'material, xom ashyo; muhim', 'Cotton is a natural material used in clothing.', 'material'),
  ('meal', 12, 'ovqat, taom, yemak', 'Breakfast is the most important meal of the day.', 'ovqat'),
  ('method', 12, 'usul, yo''l, metod', 'The teacher uses a new method to teach grammar.', 'usul'),
  ('neighbor', 12, 'qo''shni, yonidagi', 'Our neighbor is very kind and helpful.', 'qo''shni'),
  ('professional', 12, 'professional, mutaxassis', 'She is a professional translator with many skills.', 'professional'),
  ('profit', 12, 'foyda, daromad', 'The company made a large profit last year.', 'foyda'),
  ('quality', 12, 'sifat, darajasi', 'Always choose quality over quantity.', 'sifat'),
  ('shape', 12, 'shakl, ko''rinish; shakllantirmoq', 'The cake was in the shape of a star.', 'shakl'),
  ('space', 12, 'bo''shliq, joy; kosmosli', 'There is not enough space in this room.', 'bo''shliq'),
  ('stair', 12, 'pog''ona, zinalar', 'She walked up the stairs to the third floor.', 'pog''ona'),
  ('symbol', 12, 'belgi, ramz', 'The dove is a symbol of peace.', 'belgi'),
  ('thin', 12, 'ingichka, ozg''in', 'The ice on the lake is too thin to walk on.', 'ingichka'),
  ('blood', 13, 'qon, qon quyish', 'He donated blood at the hospital last week.', 'qon'),
  ('burn', 13, 'yonmoq, kuymoq; yong''in', 'Be careful not to burn your hand on the stove.', 'yonmoq'),
  ('cell', 13, 'hujayra; kamera; uyacha', 'The human body contains trillions of cells.', 'hujayra; kamera; uyacha'),
  ('contain', 13, 'o''z ichiga olmoq, saqlash', 'This box contains important documents.', 'o''z ichiga olmoq'),
  ('correct', 13, 'to''g''ri, aniq; tuzatmoq', 'Please correct your mistakes in the essay.', 'to''g''ri'),
  ('crop', 13, 'ekin, hosil; kesmoq', 'Farmers harvest their crops in autumn.', 'ekin'),
  ('demand', 13, 'talab, so''rov; talab qilmoq', 'There is a high demand for skilled workers.', 'talab'),
  ('equal', 13, 'teng, bir xil; tenglashtirmoq', 'All students have equal rights in this school.', 'teng'),
  ('feed', 13, 'oziqlantirmoq, boqmoq', 'She feeds the birds in her garden every morning.', 'oziqlantirmoq'),
  ('hole', 13, 'teshik, chuqur', 'There is a hole in the pocket of my jacket.', 'teshik'),
  ('increase', 13, 'ko''paytirmoq, oshirmoq; o''sish', 'Exercise can increase your energy levels.', 'ko''paytirmoq'),
  ('lord', 13, 'lord, xo''jayin; Allah', 'The lord of the castle invited guests to dinner.', 'lord'),
  ('owe', 13, 'qarzdor bo''lmoq, berishi kerak bo''lmoq', 'I owe you ten dollars from last week.', 'qarzdor bo''lmoq'),
  ('position', 13, 'lavozim, holat; joy', 'She applied for the position of manager.', 'lavozim'),
  ('raise', 13, 'ko''tarmoq, tarbiyalamoq', 'She raised her hand to answer the question.', 'ko''tarmoq'),
  ('responsible', 13, 'mas''ul, javobgar', 'He is responsible for locking the office door.', 'mas''ul'),
  ('sight', 13, 'ko''rish, manzara', 'The view from the top was a beautiful sight.', 'ko''rish'),
  ('spot', 13, 'dog'', joy; payqamoq', 'She spotted a rare bird in the garden.', 'dog'''),
  ('structure', 13, 'tuzilish, qurilma', 'The structure of this building is very strong.', 'tuzilish'),
  ('whole', 13, 'butun, barcha; to''liq', 'She ate the whole pizza by herself.', 'butun'),
  ('coach', 14, 'murabbiy, avtobus; o''rgatmoq', 'The coach trained the team every morning.', 'murabbiy'),
  ('control', 14, 'nazorat qilmoq, boshqarmoq', 'You need to control your emotions in stressful times.', 'nazorat qilmoq'),
  ('description', 14, 'tavsif, tasvir, ta''rif', 'Write a description of your favorite place.', 'tavsif'),
  ('direct', 14, 'to''g''ri, bevosita; boshqarmoq', 'She gave him direct instructions for the task.', 'to''g''ri'),
  ('exam', 14, 'imtihon, sinov', 'She studied all night for the final exam.', 'imtihon'),
  ('example', 14, 'misol, namuna', 'Give an example of a sentence with this word.', 'misol'),
  ('limit', 14, 'chegara, cheklov; cheklamoq', 'There is a speed limit on this road.', 'chegara'),
  ('local', 14, 'mahalliy, joydagi', 'We always buy vegetables from the local market.', 'mahalliy'),
  ('magical', 14, 'sehrli, sehr-joduli', 'The castle looked magical under the moonlight.', 'sehrli'),
  ('mail', 14, 'pochta, xat; yubormoq', 'She received a letter in the mail today.', 'pochta'),
  ('novel', 14, 'roman, kitob; yangi', 'She read a famous novel by a Russian author.', 'roman'),
  ('outline', 14, 'reja, sxema; chizib chiqmoq', 'Write an outline before starting your essay.', 'reja'),
  ('poet', 14, 'shoir, badiiy muallif', 'The poet wrote beautiful verses about nature.', 'shoir'),
  ('print', 14, 'chop etmoq, bosmoq', 'Please print two copies of this document.', 'chop etmoq'),
  ('scene', 14, 'sahna, manzara; joy', 'The crime scene was carefully examined by police.', 'sahna'),
  ('sheet', 14, 'varaq, choyshab; qatlam', 'Write your name on the top of the sheet.', 'varaq'),
  ('silly', 14, 'ahmoqona, bema''ni', 'Do not make silly mistakes in your exam.', 'ahmoqona'),
  ('store', 14, 'do''kon; saqlamoq', 'She stores her documents in a safe place.', 'do''kon; saqlamoq'),
  ('suffer', 14, 'azob chekmoq, og''riq sezmoq', 'He suffered from a serious illness for months.', 'azob chekmoq'),
  ('technology', 14, 'texnologiya, fan va texnika', 'Technology has changed the way we communicate.', 'texnologiya'),
  ('across', 15, 'narigi tomonda, kesib o''tib', 'The school is just across the street.', 'narigi tomonda'),
  ('breathe', 15, 'nafas olmoq, nafas chiqarmoq', 'Take a deep breath and breathe out slowly.', 'nafas olmoq'),
  ('characteristic', 15, 'xususiyat, belgi; xos', 'Honesty is a great characteristic to have.', 'xususiyat'),
  ('consume', 15, 'iste''mol qilmoq, sarflamoq', 'People consume a lot of plastic every year.', 'iste''mol qilmoq'),
  ('excite', 15, 'qo''zg''atmoq, hayajonga solmoq', 'The news of the trip excited all the students.', 'qo''zg''atmoq'),
  ('extreme', 15, 'ekstremal, haddan tashqari', 'The athletes trained in extreme weather conditions.', 'ekstremal'),
  ('fear', 15, 'qo''rquv, xavotir; qo''rqmoq', 'She had a strong fear of speaking in public.', 'qo''rquv'),
  ('fortunate', 15, 'omadli, baxtli', 'He was fortunate to find a good job quickly.', 'omadli'),
  ('happen', 15, 'sodir bo''lmoq, yuz bermoq', 'What happened at school today?', 'sodir bo''lmoq'),
  ('length', 15, 'uzunlik, davomiyligi', 'What is the length of this table?', 'uzunlik'),
  ('mistake', 15, 'xato, yanglishish', 'Everyone makes mistakes when learning something new.', 'xato'),
  ('observe', 15, 'kuzatmoq, nazorat qilmoq', 'Scientists observe the stars through a telescope.', 'kuzatmoq'),
  ('opportunity', 15, 'imkoniyat, fursat', 'Travel gives you the opportunity to learn new cultures.', 'imkoniyat'),
  ('prize', 15, 'mukofot, sovrin; qadrlamoq', 'She won the first prize in the art competition.', 'mukofot'),
  ('race', 15, 'irq; musobaqa; yugurish', 'He won the race with the fastest time.', 'irq; musobaqa; yugurish'),
  ('realize', 15, 'anglamoq, tushunmoq', 'She realized she had forgotten her homework.', 'anglamoq'),
  ('respond', 15, 'javob bermoq, munosabat bildirmoq', 'Please respond to the email as soon as possible.', 'javob bermoq'),
  ('risk', 15, 'xavf, xatar; xavf ostiga qo''ymoq', 'Driving too fast is a risk to everyone on the road.', 'xavf'),
  ('wonder', 15, 'ajablanmoq; mo''jiza', 'I wonder what the weather will be like tomorrow.', 'ajablanmoq; mo''jiza'),
  ('yet', 15, 'hali, lekin; allaqachon', 'She has not finished her homework yet.', 'hali'),
  ('academy', 16, 'akademiya, o''quv muassasasi', 'She studied at a music academy for five years.', 'akademiya'),
  ('ancient', 16, 'qadimiy, azaliy', 'Rome is famous for its ancient buildings.', 'qadimiy'),
  ('board', 16, 'taxtacha; kengash; minmoq', 'Write your answers on the board, please.', 'taxtacha; kengash; minmoq'),
  ('century', 16, 'asr, yuz yil', 'The building was built in the nineteenth century.', 'asr'),
  ('clue', 16, 'iz, dalil; yechim', 'The detective found an important clue at the scene.', 'iz'),
  ('concert', 16, 'konsert, musiqa kechasi', 'We attended a classical music concert last night.', 'konsert'),
  ('county', 16, 'tuman, viloyat (inglizda)', 'She works in the county government office.', 'tuman'),
  ('dictionary', 16, 'lug''at, so''zlik', 'Look up the word in the dictionary.', 'lug''at'),
  ('exist', 16, 'mavjud bo''lmoq, yashash', 'Do you believe that ghosts exist?', 'mavjud bo''lmoq'),
  ('flat', 16, 'tekis, yassi; kvartira', 'She lives in a small flat near the city center.', 'tekis'),
  ('gentleman', 16, 'janob, mulozamat bilan tutuvchi erkak', 'He was a true gentleman who helped everyone.', 'janob'),
  ('hidden', 16, 'yashirilgan, maxfiy', 'The treasure was hidden under a large rock.', 'yashirilgan'),
  ('maybe', 16, 'balki, ehtimol', 'Maybe we can go to the park this afternoon.', 'balki'),
  ('officer', 16, 'ofitser; xodim, mansabdor shaxs', 'The police officer helped the lost child.', 'ofitser; xodim'),
  ('original', 16, 'asl, original; dastlabki', 'This painting is an original work of art.', 'asl'),
  ('pound', 16, 'funt; urib maydalash', 'She bought one pound of flour at the market.', 'funt; urib maydalash'),
  ('process', 16, 'jarayon, bosqich; qayta ishlash', 'Learning a language is a long process.', 'jarayon'),
  ('publish', 16, 'nashr etmoq, chop qilmoq', 'She published her first book at age twenty-five.', 'nashr etmoq'),
  ('theater', 16, 'teatr, kino; operatsiya xonasi', 'We watched a play at the local theater.', 'teatr'),
  ('wealth', 16, 'boylik, mol-mulk', 'Health is more important than wealth.', 'boylik'),
  ('appreciate', 17, 'qadrlash, minnatdorchilik bildirmoq', 'I really appreciate your help today.', 'qadrlash'),
  ('available', 17, 'mavjud, bo''sh, olish mumkin', 'Is the manager available for a meeting now?', 'mavjud'),
  ('beat', 17, 'urmoq, mag''lub etmoq; ritm', 'Our team beat the other team five to two.', 'urmoq'),
  ('bright', 17, 'yorqin, aqlli; ravshan', 'She is a bright student with great potential.', 'yorqin'),
  ('celebrate', 17, 'nishonlamoq, bayram qilmoq', 'We celebrated her birthday with a big cake.', 'nishonlamoq'),
  ('determine', 17, 'aniqlash, hal qilmoq', 'Scientists try to determine the age of fossils.', 'aniqlash'),
  ('disappear', 17, 'yo''qolmoq, g''oyib bo''lmoq', 'The magician made the rabbit disappear.', 'yo''qolmoq'),
  ('else', 17, 'boshqa, yana; aks holda', 'Is there anything else I can help you with?', 'boshqa'),
  ('fair', 17, 'adolatli, to''g''ri; ko''rgazma', 'The teacher gave everyone a fair chance to speak.', 'adolatli'),
  ('flow', 17, 'oqmoq, oqish; ravon bo''lmoq', 'The river flows slowly through the valley.', 'oqmoq'),
  ('forward', 17, 'oldinga, kelajakka', 'Please move forward and find a seat at the front.', 'oldinga'),
  ('hill', 17, 'tepalik, do''nglik', 'She climbed the hill to enjoy the view.', 'tepalik'),
  ('level', 17, 'daraja, sath; tekis', 'What level is your English course?', 'daraja'),
  ('lone', 17, 'yolg''iz, bitta', 'A lone traveler walked along the empty road.', 'yolg''iz'),
  ('puddle', 17, 'ko''lmak, suv to''planishi', 'Children love jumping in puddles after rain.', 'ko''lmak'),
  ('response', 17, 'javob, munosabat', 'We are waiting for a response to our email.', 'javob'),
  ('season', 17, 'fasl, mavsim', 'Spring is my favorite season of the year.', 'fasl'),
  ('solution', 17, 'yechim, echim; eritma', 'We need to find a solution to this problem.', 'yechim'),
  ('waste', 17, 'isrof qilmoq, chiqindi', 'Do not waste water, it is very precious.', 'isrof qilmoq'),
  ('whether', 17, 'yo yoki; yoki-yoki', 'I am not sure whether she will come today.', 'yo yoki; yoki-yoki'),
  ('argue', 18, 'bahslashmoq, tortishmoq', 'They argued about which film to watch.', 'bahslashmoq'),
  ('communicate', 18, 'muloqot qilmoq, aloqa o''rnatmoq', 'It is important to communicate clearly at work.', 'muloqot qilmoq'),
  ('crowd', 18, 'olomon, to''da; to''planmoq', 'A large crowd gathered to watch the concert.', 'olomon'),
  ('depend', 18, 'bog''liq bo''lmoq, ishonmoq', 'Your results depend on how hard you study.', 'bog''liq bo''lmoq'),
  ('dish', 18, 'idish; taom', 'She cooked a delicious dish for the dinner party.', 'idish; taom'),
  ('empty', 18, 'bo''sh, hech narsa yo''q; bo''shatmoq', 'The classroom was empty when I arrived.', 'bo''sh'),
  ('exact', 18, 'aniq, to''g''ri; aynan', 'I do not remember the exact time of the meeting.', 'aniq'),
  ('fresh', 18, 'yangi, toza', 'Fresh vegetables are better than canned ones.', 'yangi'),
  ('gather', 18, 'yig''ilmoq, to''planmoq', 'The family gathers every Sunday for dinner.', 'yig''ilmoq'),
  ('indicate', 18, 'ko''rsatmoq, bildirmoq', 'The sign indicates that parking is not allowed here.', 'ko''rsatmoq'),
  ('item', 18, 'narsa, mahsulot; modda', 'Please check every item on the list.', 'narsa'),
  ('offer', 18, 'taklif qilmoq, bermoq; taklif', 'He offered to help carry the heavy bags.', 'taklif qilmoq'),
  ('price', 18, 'narx, qiymat', 'The price of food has increased this year.', 'narx'),
  ('product', 18, 'mahsulot, tovar', 'This company makes high-quality dairy products.', 'mahsulot'),
  ('property', 18, 'mulk, yer; xususiyat', 'She owns a property in the north of the city.', 'mulk'),
  ('purchase', 18, 'sotib olmoq; xarid', 'She purchased a new laptop for her studies.', 'sotib olmoq; xarid'),
  ('recommend', 18, 'tavsiya qilmoq, maslahat bermoq', 'I recommend this restaurant for a special dinner.', 'tavsiya qilmoq'),
  ('select', 18, 'tanlash, ajratib olmoq', 'Select the correct answer from the options below.', 'tanlash'),
  ('tool', 18, 'asbob, qurol; vosita', 'A hammer is a common tool used in construction.', 'asbob'),
  ('treat', 18, 'muomala qilmoq; davolash; siylash', 'Treat others the way you want to be treated.', 'muomala qilmoq; davolash; siylash'),
  ('alive', 19, 'tirik, hayot; faol', 'Luckily, all the passengers survived and were alive.', 'tirik'),
  ('bone', 19, 'suyak', 'She broke a bone in her arm while playing sport.', 'suyak'),
  ('bother', 19, 'bezovta qilmoq, tashvishga solmoq', 'I am sorry to bother you, but I need help.', 'bezovta qilmoq'),
  ('captain', 19, 'kapitan, rahbar', 'The captain of the ship gave orders to the crew.', 'kapitan'),
  ('conclusion', 19, 'xulosa, yakun', 'The conclusion of the essay must be clear.', 'xulosa'),
  ('doubt', 19, 'shubha, gumon; shubhalanmoq', 'I have no doubt that she will succeed.', 'shubha'),
  ('explore', 19, 'o''rganmoq, kashf etmoq', 'Scientists explore the ocean floor for new species.', 'o''rganmoq'),
  ('foreign', 19, 'xorijiy, chet el', 'She is studying a foreign language at university.', 'xorijiy'),
  ('glad', 19, 'xursand, mamnun', 'I am glad to hear that you passed the exam.', 'xursand'),
  ('however', 19, 'lekin, biroq; shunga qaramay', 'He studied hard; however, he failed the test.', 'lekin'),
  ('injustice', 19, 'adolatsizlik, huquq buzilishi', 'She fought against injustice in her community.', 'adolatsizlik'),
  ('international', 19, 'xalqaro, davlatlararo', 'She works for an international organization.', 'xalqaro'),
  ('lawyer', 19, 'advokat, yurist', 'She hired a lawyer to help with her case.', 'advokat'),
  ('mention', 19, 'eslatmoq, aytib o''tmoq', 'He mentioned that he would be late for class.', 'eslatmoq'),
  ('policy', 19, 'siyosat, qoida; yo''riqnoma', 'The school has a strict policy on mobile phones.', 'siyosat'),
  ('social', 19, 'ijtimoiy, jamoatchilik', 'She has strong social skills and many friends.', 'ijtimoiy'),
  ('speech', 19, 'nutq, so''zlash; rech', 'She gave a powerful speech at the graduation ceremony.', 'nutq'),
  ('staff', 19, 'xodimlar, hodimlar', 'The hotel staff was very helpful during our stay.', 'xodimlar'),
  ('toward', 19, 'tomon, yo''nalishida', 'She walked toward the exit of the building.', 'tomon'),
  ('wood', 19, 'yog''och, o''rmon; daraxt', 'The house was built with wood from a local forest.', 'yog''och'),
  ('achieve', 20, 'erishmoq, amalga oshirmoq', 'She achieved her goal of becoming a doctor.', 'erishmoq'),
  ('advise', 20, 'maslahat bermoq, o''gitlamoq', 'He advised me to study harder for the next exam.', 'maslahat bermoq'),
  ('already', 20, 'allaqachon, endi', 'She has already finished her homework.', 'allaqachon'),
  ('basic', 20, 'asosiy, boshlang''ich', 'You need a basic knowledge of English.', 'asosiy'),
  ('bit', 20, 'bir oz, bo''lak; bir parcha', 'She felt a bit nervous before the presentation.', 'bir oz'),
  ('consider', 20, 'ko''rib chiqmoq, hisobga olmoq', 'Please consider all the options before deciding.', 'ko''rib chiqmoq'),
  ('destroy', 20, 'yo''q qilmoq, buzmoq', 'The fire destroyed several houses in the village.', 'yo''q qilmoq'),
  ('entertain', 20, 'ko''ngil ocharmoq, quvontirmoq', 'The clown entertained the children at the party.', 'ko''ngil ocharmoq'),
  ('extra', 20, 'qo''shimcha, ortiqcha', 'She always brings extra pens to the exam.', 'qo''shimcha'),
  ('goal', 20, 'maqsad, niyat; gol', 'His goal is to become a professional footballer.', 'maqsad'),
  ('lie', 20, 'yolg''on gapirmoq; yotmoq', 'Do not lie about your age on the application.', 'yolg''on gapirmoq; yotmoq'),
  ('meat', 20, 'go''sht, et', 'She does not eat meat because she is vegetarian.', 'go''sht'),
  ('opinion', 20, 'fikr, mulohaza', 'In my opinion, reading is the best way to learn.', 'fikr'),
  ('real', 20, 'haqiqiy, asl, chin', 'Is that a real diamond in her ring?', 'haqiqiy'),
  ('reflect', 20, 'aks ettirmoq; o''ylamoq', 'The lake reflects the mountains in the distance.', 'aks ettirmoq; o''ylamoq'),
  ('regard', 20, 'hisoblamoq; nazar; salom', 'He is regarded as one of the best students.', 'hisoblamoq; nazar; salom'),
  ('serve', 20, 'xizmat qilmoq; uzatmoq', 'The waiter served the food very quickly.', 'xizmat qilmoq; uzatmoq'),
  ('vegetable', 20, 'sabzavot, o''simlik', 'Eat more vegetables to stay healthy.', 'sabzavot'),
  ('war', 20, 'urush, jang', 'The war lasted for many years and caused great suffering.', 'urush'),
  ('worth', 20, 'qimmat, qadrli; arziydigan', 'This book is worth reading more than once.', 'qimmat');
