-- word_entries ga so'zlarni qo'shish - Kunlar 21-30
-- Bu faylni Supabase SQL Editor'da alohida ishga tushiring

INSERT INTO word_entries (word, day_number, meaning, example, synonym) VALUES
  ('appear', 21, 'ko''rinmoq, paydo bo''lmoq', 'Stars appear in the sky after sunset.', 'ko''rinmoq'),
  ('base', 21, 'asos, tub; joylashmoq', 'The base of the triangle must be measured.', 'asos'),
  ('brain', 21, 'miya, ong; aql', 'Regular exercise is good for the brain.', 'miya'),
  ('career', 21, 'kasb, martaba, faoliyat', 'She built a successful career in medicine.', 'kasb'),
  ('clerk', 21, 'kotib, menejer; do''kon xodimi', 'The clerk helped the customer find the right size.', 'kotib'),
  ('effort', 21, 'harakat, kuch sarflash', 'She put a lot of effort into her final project.', 'harakat'),
  ('enter', 21, 'kirmoq, qatnashmoq', 'Please knock before you enter the room.', 'kirmoq'),
  ('excellent', 21, 'a''lo, zo''r, mukammal', 'She received excellent marks in all her subjects.', 'a''lo'),
  ('hero', 21, 'qahramon, bahodir', 'The firefighter was called a hero for saving lives.', 'qahramon'),
  ('hurry', 21, 'shoshmoq, tezlashmoq; shoshilinch', 'We need to hurry or we will miss the bus.', 'shoshmoq'),
  ('inform', 21, 'xabar bermoq, ma''lum qilmoq', 'Please inform me when the results are ready.', 'xabar bermoq'),
  ('later', 21, 'keyinroq, undan keyin', 'I will call you later this evening.', 'keyinroq'),
  ('leave', 21, 'ketmoq; tark etmoq; ruxsat', 'She left home early to avoid the traffic.', 'ketmoq; tark etmoq; ruxsat'),
  ('locate', 21, 'joylashuv aniqlash, topmoq', 'Can you locate the city on this map?', 'joylashuv aniqlash'),
  ('nurse', 21, 'hamshira; parvarish qilmoq', 'The nurse took care of the patient all night.', 'hamshira; parvarish qilmoq'),
  ('operation', 21, 'operatsiya, amal; harakat', 'The doctor performed a three-hour operation.', 'operatsiya'),
  ('pain', 21, 'og''riq, azob; dard', 'She felt a sharp pain in her back.', 'og''riq'),
  ('refuse', 21, 'rad etmoq, inkor qilmoq', 'He refused to answer the question in class.', 'rad etmoq'),
  ('though', 21, 'garchi, biroq, lekin', 'Though it was raining, we continued our walk.', 'garchi'),
  ('various', 21, 'turli, har xil', 'The shop sells various types of fruit.', 'turli'),
  ('actual', 22, 'haqiqiy, aslida', 'The actual cost of the trip was more than expected.', 'haqiqiy'),
  ('amaze', 22, 'hayratga solmoq, lol qoldirmoq', 'Her performance amazed everyone in the audience.', 'hayratga solmoq'),
  ('charge', 22, 'to''lov, narx; zaryadlamoq; yuklash', 'There is no charge for children under five.', 'to''lov'),
  ('comfort', 22, 'qulaylik, tasalli; tasalli bermoq', 'A warm cup of tea brings great comfort.', 'qulaylik'),
  ('contact', 22, 'aloqa, muloqot; bog''lanmoq', 'Please contact us if you have any questions.', 'aloqa'),
  ('customer', 22, 'mijoz, xaridor', 'The store always tries to satisfy its customers.', 'mijoz'),
  ('deliver', 22, 'yetkazib bermoq, topshirmoq', 'The postman delivered a package this morning.', 'yetkazib bermoq'),
  ('earn', 22, 'topmoq, ishlab olmoq', 'She earns a good salary as a software engineer.', 'topmoq'),
  ('gate', 22, 'darvoza, eshik; yo''lak', 'Please wait at the gate before boarding the plane.', 'darvoza'),
  ('include', 22, 'o''z ichiga olmoq, qo''shmoq', 'The price includes breakfast and dinner.', 'o''z ichiga olmoq'),
  ('manage', 22, 'boshqarmoq, uddalash', 'She managed to finish the report before the deadline.', 'boshqarmoq'),
  ('mystery', 22, 'sir, jumboq, sirliq', 'The mystery of the missing keys was never solved.', 'sir'),
  ('occur', 22, 'sodir bo''lmoq, yuz bermoq', 'Earthquakes often occur along fault lines.', 'sodir bo''lmoq'),
  ('opposite', 22, 'qarama-qarshi, teskari', 'The bank is on the opposite side of the street.', 'qarama-qarshi'),
  ('plate', 22, 'likop, tarelka; qatlam', 'She put a plate of fruit on the table.', 'likop'),
  ('receive', 22, 'olmoq, qabul qilmoq', 'She received a letter from her university today.', 'olmoq'),
  ('reward', 22, 'mukofot, taqdirlamoq', 'Hard work always brings its own reward.', 'mukofot'),
  ('set', 22, 'o''rnatmoq; to''plam; botmoq', 'She set the alarm for six in the morning.', 'o''rnatmoq; to''plam; botmoq'),
  ('steal', 22, 'o''g''irlamoq, urchmoq', 'Someone stole his wallet on the bus.', 'o''g''irlamoq'),
  ('thief', 22, 'o''g''ri, qaroqchi', 'The thief was caught by the police at the market.', 'o''g''ri'),
  ('advance', 23, 'ilgarilamoq, rivojlanmoq; oldindan', 'Technology continues to advance every year.', 'ilgarilamoq'),
  ('athlete', 23, 'sportchi, atlet', 'She is a talented athlete who trains every day.', 'sportchi'),
  ('average', 23, 'o''rtacha, oddiy; o''rtacha hisob', 'The average temperature in summer is 35 degrees.', 'o''rtacha'),
  ('behavior', 23, 'xulq-atvor, harakat', 'Good behavior is expected from all students.', 'xulq-atvor'),
  ('behind', 23, 'orqada, keyin; sabab sifatida', 'She sat behind the tallest student in class.', 'orqada'),
  ('course', 23, 'kurs, dars; yo''nalish; tabiiy ravishda', 'She enrolled in an English course last month.', 'kurs'),
  ('lower', 23, 'pastroq, kamroq; tushirmoq', 'Please lower your voice in the library.', 'pastroq'),
  ('match', 23, 'mos kelmoq; musobaqa; gugurt', 'The colors of your shoes match your jacket.', 'mos kelmoq; musobaqa; gugurt'),
  ('member', 23, 'a''zo, ishtirokchi', 'She became a member of the school choir.', 'a''zo'),
  ('mental', 23, 'aqliy, psixologik', 'Regular rest is important for good mental health.', 'aqliy'),
  ('passenger', 23, 'yo''lovchi, musofir', 'All passengers must fasten their seatbelts.', 'yo''lovchi'),
  ('personality', 23, 'shaxsiyat, xarakter', 'She has a warm and friendly personality.', 'shaxsiyat'),
  ('poem', 23, 'she''r, nazmiy asar', 'He wrote a beautiful poem about the mountains.', 'she''r'),
  ('pole', 23, 'ustun, qutb; tayoq', 'The flag was tied to a tall metal pole.', 'ustun'),
  ('remove', 23, 'olib tashlamoq, yo''qotmoq', 'Please remove your shoes before entering.', 'olib tashlamoq'),
  ('safety', 23, 'xavfsizlik, omon-esen', 'Always wear a helmet for safety when cycling.', 'xavfsizlik'),
  ('shoot', 23, 'otmoq, rasga olmoq', 'The photographer shot amazing photos in the forest.', 'otmoq'),
  ('sound', 23, 'tovush, ovoz; sog''lom; eshitilmoq', 'The sound of the rain helped her fall asleep.', 'tovush'),
  ('swim', 23, 'suzmoq, cho''milmoq', 'She swims in the pool every morning.', 'suzmoq'),
  ('web', 23, 'to''r, o''rgimchak to''ri; internet', 'The spider built a delicate web in the corner.', 'to''r'),
  ('block', 24, 'to''siq, blok; to''sib qo''ymoq', 'A fallen tree blocked the road completely.', 'to''siq'),
  ('cheer', 24, 'mamnunlik; rag''batlantirmoq; xursandlik', 'The crowd cheered loudly when the team scored.', 'mamnunlik; rag''batlantirmoq; xursandlik'),
  ('complex', 24, 'murakkab, qiyin; majmua', 'The math problem was too complex for beginners.', 'murakkab'),
  ('critic', 24, 'tanqidchi, munaqqid', 'The film received mixed reviews from critics.', 'tanqidchi'),
  ('event', 24, 'tadbir, voqea; hodisa', 'The school held a cultural event last Friday.', 'tadbir'),
  ('exercise', 24, 'mashq, jismoniy tarbiya; bajarmoq', 'Daily exercise helps improve your health.', 'mashq'),
  ('fit', 24, 'mos kelmoq; sog''lom; sig''moq', 'The new dress fits her perfectly.', 'mos kelmoq; sog''lom; sig''moq'),
  ('friendship', 24, 'do''stlik, birodarlik', 'Their friendship lasted for more than thirty years.', 'do''stlik'),
  ('guide', 24, 'yo''lboshchi; qo''llanma; boshqarmoq', 'The guide led us through the old part of the city.', 'yo''lboshchi; qo''llanma; boshqarmoq'),
  ('lack', 24, 'yetishmovchilik, kamchilik', 'A lack of sleep affects your concentration.', 'yetishmovchilik'),
  ('passage', 24, 'o''tish, yo''lak; matn', 'Read the passage and answer the questions below.', 'o''tish'),
  ('perform', 24, 'ijro etmoq, ko''rsatmoq', 'She performed a beautiful dance at the ceremony.', 'ijro etmoq'),
  ('pressure', 24, 'bosim, tazyiq; bosmoq', 'He worked well under pressure and met the deadline.', 'bosim'),
  ('probable', 24, 'ehtimoliy, kutilayotgan', 'Rain is probable in the evening.', 'ehtimoliy'),
  ('public', 24, 'ommaviy, jamoat; jamiyat', 'She spoke in public for the first time at school.', 'ommaviy'),
  ('strike', 24, 'zarba; ish tashlash; urmoq', 'The workers decided to go on strike for better pay.', 'zarba; ish tashlash; urmoq'),
  ('support', 24, 'qo''llab-quvvatlamoq; tayanch', 'Her family always supports her decisions.', 'qo''llab-quvvatlamoq; tayanch'),
  ('task', 24, 'vazifa, topshiriq', 'Complete all the tasks before the end of the class.', 'vazifa'),
  ('term', 24, 'atama; muddat; semestr', 'The school term starts in September every year.', 'atama; muddat; semestr'),
  ('unite', 24, 'birlashmoq, birlashtirmoq', 'The two teams united to win the championship.', 'birlashmoq'),
  ('associate', 25, 'bog''lash, qo''shmoq; hamkasb', 'People often associate the color red with danger.', 'bog''lash'),
  ('environment', 25, 'atrof-muhit, muhit', 'We must protect the environment for future generations.', 'atrof-muhit'),
  ('factory', 25, 'zavod, fabrika', 'The factory produces over a thousand cars every day.', 'zavod'),
  ('feature', 25, 'xususiyat; belgi; ko''rsatmoq', 'One great feature of this phone is its camera.', 'xususiyat; belgi; ko''rsatmoq'),
  ('instance', 25, 'misol, holat; masalan', 'For instance, she speaks three foreign languages.', 'misol'),
  ('involve', 25, 'o''z ichiga olmoq, jalb etmoq', 'The project involves a lot of research and planning.', 'o''z ichiga olmoq'),
  ('medicine', 25, 'dori, dorivor; tibbiyot', 'Take this medicine twice a day after meals.', 'dori'),
  ('mix', 25, 'aralashmoq, qo''shmoq; aralashma', 'Mix the flour and sugar together in a bowl.', 'aralashmoq'),
  ('organize', 25, 'tashkil etmoq, tartiblashtirmoq', 'She organized a surprise party for her friend.', 'tashkil etmoq'),
  ('period', 25, 'davr, muddat; nuqta', 'She studied art during the Renaissance period.', 'davr'),
  ('populate', 25, 'aholi bilan to''ldirmoq, yashamoq', 'The region is densely populated.', 'aholi bilan to''ldirmoq'),
  ('produce', 25, 'ishlab chiqarmoq, yaratmoq; mahsulot', 'This farm produces organic vegetables.', 'ishlab chiqarmoq'),
  ('range', 25, 'oraliq, ko''lam; keng qamrov', 'The shop sells a wide range of products.', 'oraliq'),
  ('recognize', 25, 'tanish, aniqlash; tan olmoq', 'I recognized her voice on the phone immediately.', 'tanish'),
  ('regular', 25, 'muntazam, doimiy; oddiy', 'Regular practice is the key to improvement.', 'muntazam'),
  ('sign', 25, 'belgi, imo; imzo; imzolamoq', 'She made a sign that said Welcome for the party.', 'belgi'),
  ('tip', 25, 'maslahat; uchi; choy puli', 'Her teacher gave her useful tips for the exam.', 'maslahat; uchi; choy puli'),
  ('tradition', 25, 'an''ana, urf-odat', 'It is a tradition to give gifts on birthdays.', 'an''ana'),
  ('trash', 25, 'axlat, chiqit; chiqit qilmoq', 'Please put the trash in the bin outside.', 'axlat'),
  ('wide', 25, 'keng, katta; bir tomondan boshqasigacha', 'The river is very wide at this point.', 'keng'),
  ('advice', 26, 'maslahat, tavsiya', 'She gave me useful advice about studying English.', 'maslahat'),
  ('along', 26, 'bo''ylab, birga', 'They walked along the river in the evening.', 'bo''ylab'),
  ('attention', 26, 'e''tibor, diqqat', 'Please pay attention to the teacher''s explanation.', 'e''tibor'),
  ('attract', 26, 'jalb etmoq, qiziqtirmoq', 'The colorful display attracted many customers.', 'jalb etmoq'),
  ('climb', 26, 'chiqmoq, tirmoashmoq', 'She climbed to the top of the tall ladder.', 'chiqmoq'),
  ('drop', 26, 'tushirmoq, tomchilamoq; pasaymoq', 'She dropped her pen on the floor.', 'tushirmoq'),
  ('final', 26, 'yakuniy, oxirgi; final', 'The final exam will be held next Friday.', 'yakuniy'),
  ('further', 26, 'bundan tashqari; uzoqroq', 'Can you explain this idea further, please?', 'bundan tashqari; uzoqroq'),
  ('imply', 26, 'nazarda tutmoq, anglatmoq', 'Her silence implied that she was unhappy.', 'nazarda tutmoq'),
  ('maintain', 26, 'saqlash, ushlab turmoq', 'It is important to maintain a healthy lifestyle.', 'saqlash'),
  ('neither', 26, 'na biri, na boshqasi; ham emas', 'Neither of the answers was correct.', 'na biri'),
  ('otherwise', 26, 'aks holda, boshqacha', 'Study hard; otherwise, you will fail the exam.', 'aks holda'),
  ('physical', 26, 'jismoniy, fizikaviy', 'Regular physical activity improves your health.', 'jismoniy'),
  ('prove', 26, 'isbotlamoq, ko''rsatmoq', 'She proved that hard work leads to success.', 'isbotlamoq'),
  ('react', 26, 'munosabat bildirmoq, javob bermoq', 'How did she react when she heard the news?', 'munosabat bildirmoq'),
  ('ride', 26, 'minmoq, yurishmoq; sayohat', 'She rides her bike to school every morning.', 'minmoq'),
  ('situated', 26, 'joylashgan, turgan', 'The hotel is situated near the city center.', 'joylashgan'),
  ('society', 26, 'jamiyat, ijtimoiy hayot', 'Education plays a key role in a healthy society.', 'jamiyat'),
  ('standard', 26, 'standart, me''yor; darajasi', 'The school has very high academic standards.', 'standart'),
  ('suggest', 26, 'taklif etmoq, maslahat bermoq', 'She suggested meeting at the library to study.', 'taklif etmoq'),
  ('actually', 27, 'aslida, haqiqatda', 'I actually enjoyed the difficult exam.', 'aslida'),
  ('bite', 27, 'tishlamoq, chaqqan; tishlay', 'The dog bit the postman on the leg.', 'tishlamoq'),
  ('coast', 27, 'qirg''oq, sohill', 'They drove along the coast and enjoyed the view.', 'qirg''oq'),
  ('deal', 27, 'kelishuv, bitim; muomala qilmoq', 'They made a deal to share the work equally.', 'kelishuv'),
  ('desert', 27, 'cho''l, sahro; tark etmoq', 'The camel is well adapted to life in the desert.', 'cho''l'),
  ('earthquake', 27, 'zilzila, yer silkinishi', 'The earthquake damaged many buildings in the city.', 'zilzila'),
  ('effective', 27, 'samarali, natijali', 'She uses an effective method to learn vocabulary.', 'samarali'),
  ('examine', 27, 'ko''rib chiqmoq, tekshirmoq', 'The doctor examined the patient carefully.', 'ko''rib chiqmoq'),
  ('false', 27, 'yolg''on, noto''g''ri', 'The news report turned out to be completely false.', 'yolg''on'),
  ('gift', 27, 'sovg''a; iste''dod', 'She gave her mother a beautiful gift for her birthday.', 'sovg''a; iste''dod'),
  ('hunger', 27, 'och qolish, ishtaha; chanqoqlik', 'World hunger is a major global problem.', 'och qolish'),
  ('imagine', 27, 'tasavvur qilmoq, ko''z oldiga keltirmoq', 'Imagine living on another planet in the future.', 'tasavvur qilmoq'),
  ('journey', 27, 'safar, sayohat', 'The journey from Tashkent to Samarkand takes three hours.', 'safar'),
  ('puzzle', 27, 'jumboq, topishmoq; sarosimaga tushirmoq', 'She enjoys solving crossword puzzles.', 'jumboq'),
  ('quite', 27, 'ancha, juda; bir oz', 'The test was quite difficult for most students.', 'ancha'),
  ('rather', 27, 'aksincha, biroz; nisbatan', 'She would rather read than watch television.', 'aksincha'),
  ('specific', 27, 'aniq, muayyan; maxsus', 'Please give a specific example to support your answer.', 'aniq'),
  ('tour', 27, 'sayohat, tur; gastrol', 'They went on a guided tour of the old city.', 'sayohat'),
  ('trip', 27, 'sayohat, safarcha; qoqilish', 'Our class went on a trip to the science museum.', 'sayohat'),
  ('value', 27, 'qiymat, qadr; qadrlash', 'Education has a high value in our culture.', 'qiymat'),
  ('band', 28, 'guruh, to''da; lenta; birikmoq', 'Her favorite band is performing live tonight.', 'guruh'),
  ('barely', 28, 'zo''rg''a, qiyinchilik bilan', 'She barely had enough time to finish the exam.', 'zo''rg''a'),
  ('boring', 28, 'zeriktiradigan, qiziqarsiz', 'The lecture was so boring that he fell asleep.', 'zeriktiradigan'),
  ('cancel', 28, 'bekor qilmoq, rad etmoq', 'The flight was cancelled due to bad weather.', 'bekor qilmoq'),
  ('driveway', 28, 'yo''lakcha, avtomobil yo''li', 'She parked her car in the driveway.', 'yo''lakcha'),
  ('garbage', 28, 'axlat, chiqit', 'Please take out the garbage before you leave.', 'axlat'),
  ('instrument', 28, 'musiqa asbobi; asbob; qurol', 'She plays the piano and one other instrument.', 'musiqa asbobi; asbob; qurol'),
  ('list', 28, 'ro''yxat; ro''yxatga kiritmoq', 'Write a list of the vocabulary words you know.', 'ro''yxat; ro''yxatga kiritmoq'),
  ('magic', 28, 'sehrgari; sehr; mo''jizakor', 'The magician performed amazing magic tricks.', 'sehrgari; sehr; mo''jizakor'),
  ('message', 28, 'xabar, habar; mazmun', 'She left a message on my phone last night.', 'xabar'),
  ('notice', 28, 'e''tibor bermoq, payqamoq; e''lon', 'Did you notice the new sign on the door?', 'e''tibor bermoq'),
  ('own', 28, 'o''ziga tegishli; egalik qilmoq', 'She owns a small bakery in the old part of town.', 'o''ziga tegishli; egalik qilmoq'),
  ('predict', 28, 'bashorat qilmoq, oldindan aytmoq', 'Scientists try to predict future climate changes.', 'bashorat qilmoq'),
  ('professor', 28, 'professor, o''qituvchi', 'The professor explained the theory clearly.', 'professor'),
  ('rush', 28, 'shoshmoq, yugurmoq; to''lqin', 'There is no need to rush; we have enough time.', 'shoshmoq'),
  ('schedule', 28, 'jadval, reja; rejalashtirilgan', 'She checked her schedule before the meeting.', 'jadval'),
  ('share', 28, 'ulashmoq, bo''lishmoq; ulush', 'Please share your ideas with the rest of the class.', 'ulashmoq'),
  ('stage', 28, 'sahna; bosqich; darajasi', 'The final stage of the project was the hardest.', 'sahna; bosqich; darajasi'),
  ('storm', 28, 'bo''ron, dovul; hujum', 'The storm knocked down many trees in the park.', 'bo''ron'),
  ('within', 28, 'ichida, vaqt ichida; doirasida', 'Please complete the task within thirty minutes.', 'ichida'),
  ('advertise', 29, 'reklama qilmoq, e''lon bermoq', 'They advertised the new product on television.', 'reklama qilmoq'),
  ('assign', 29, 'topshirmoq, belgilamoq', 'The teacher assigned a reading task for homework.', 'topshirmoq'),
  ('audience', 29, 'auditoriya, tomoshabin; tinglovchi', 'The audience clapped loudly after the performance.', 'auditoriya'),
  ('breakfast', 29, 'nonushta, ertalabki ovqat', 'She always has a healthy breakfast before school.', 'nonushta'),
  ('competition', 29, 'musobaqa, tanlov; raqobat', 'She won first place in the national writing competition.', 'musobaqa'),
  ('cool', 29, 'salqin; zo''r, ajoyib; sovitmoq', 'It is cool to wear a jacket in the evening.', 'salqin; zo''r'),
  ('gain', 29, 'olmoq, qozonmoq; foyda', 'She gained a lot of knowledge from traveling.', 'olmoq'),
  ('importance', 29, 'muhimlik, ahamiyat', 'She spoke about the importance of daily exercise.', 'muhimlik'),
  ('knowledge', 29, 'bilim, ma''lumot', 'Reading books is the best way to gain knowledge.', 'bilim'),
  ('major', 29, 'asosiy, katta; mutaxassislik', 'She chose history as her major at university.', 'asosiy'),
  ('mean', 29, 'anglatmoq; o''rtacha; xasis', 'What does this word mean in English?', 'anglatmoq; o''rtacha; xasis'),
  ('prefer', 29, 'afzal ko''rmoq, yoqtirmoq', 'She prefers tea to coffee in the morning.', 'afzal ko''rmoq'),
  ('president', 29, 'prezident, rais', 'She was elected president of the student council.', 'prezident'),
  ('progress', 29, 'rivojlanish, muvaffaqiyat; oldinga bormoq', 'She made great progress in her English lessons.', 'rivojlanish'),
  ('respect', 29, 'hurmat; hurmat qilmoq', 'Always show respect to your teachers and elders.', 'hurmat; hurmat qilmoq'),
  ('rich', 29, 'boy, serob; to''yimli', 'She comes from a rich family but lives simply.', 'boy'),
  ('skill', 29, 'ko''nikma, mahorat', 'Writing is an important skill for university students.', 'ko''nikma'),
  ('somehow', 29, 'qandaydir, bir yo''l bilan', 'She somehow managed to finish everything on time.', 'qandaydir'),
  ('strength', 29, 'kuch, quvvat; qodir bo''lish', 'Hard work and patience are her greatest strengths.', 'kuch'),
  ('vote', 29, 'ovoz bermoq; ovoz; saylov', 'Everyone has the right to vote in an election.', 'ovoz bermoq; ovoz; saylov'),
  ('above', 30, 'ustida, tepasida; yuqorida', 'The temperature rose above forty degrees yesterday.', 'ustida'),
  ('ahead', 30, 'oldinda, kelajakda', 'She is ahead of the other students in English.', 'oldinda'),
  ('amount', 30, 'miqdor, ko''lam; jamlab', 'A small amount of sugar is enough for this recipe.', 'miqdor'),
  ('belief', 30, 'e''tiqod, ishonch; yondashuv', 'Her belief in hard work helped her succeed.', 'e''tiqod'),
  ('center', 30, 'markaz, o''rta; markaziy', 'The shopping center is in the middle of the city.', 'markaz'),
  ('common', 30, 'umumiy, keng tarqalgan; odatiy', 'English is a common language used around the world.', 'umumiy'),
  ('cost', 30, 'narx, xarajat; turmoq', 'The cost of living has increased significantly.', 'narx'),
  ('demonstrate', 30, 'ko''rsatmoq, isbotlamoq', 'She demonstrated how to solve the problem step by step.', 'ko''rsatmoq'),
  ('different', 30, 'farqli, boshqa; turli', 'People learn in many different ways.', 'farqli'),
  ('evidence', 30, 'dalil, isbot; ko''rsatmoq', 'The lawyer presented clear evidence in court.', 'dalil'),
  ('honesty', 30, 'halollik, to''g''rilik', 'Honesty is the most important quality in a friend.', 'halollik'),
  ('idiom', 30, 'idioma, frazeologik birlik', 'She learns one new idiom in English every day.', 'idioma'),
  ('independent', 30, 'mustaqil, o''z-o''zicha', 'She is an independent learner who studies alone.', 'mustaqil'),
  ('inside', 30, 'ichida, ichki qism; kirish', 'Please wait inside until the rain stops.', 'ichida'),
  ('master', 30, 'ustoz, mahoratli; egalamoq', 'It takes years to master a foreign language.', 'ustoz'),
  ('memory', 30, 'xotira, eslab qolish; yodgorlik', 'She has an excellent memory for vocabulary.', 'xotira'),
  ('proper', 30, 'to''g''ri, mos; tegishli', 'Always use proper grammar when writing formally.', 'to''g''ri'),
  ('scan', 30, 'skanerlash; ko''zdan kechirmoq', 'She scanned the document and sent it by email.', 'skanerlash; ko''zdan kechirmoq'),
  ('section', 30, 'bo''lim, qism; kesma', 'Read the first section of the chapter carefully.', 'bo''lim'),
  ('surface', 30, 'yuza, sirt; ustki qism', 'The surface of the table was scratched.', 'yuza');
