-- word_entries ga so'zlarni qo'shish - Kunlar 1-10
-- Bu faylni Supabase SQL Editor'da alohida ishga tushiring

INSERT INTO word_entries (word, day_number, meaning, example, synonym) VALUES
  ('afraid', 1, 'qo''rqqan, xavotirda', 'She was afraid of the dark room.', 'qo''rqqan'),
  ('agree', 1, 'rozi bo''lmoq, kelishmoq', 'I agree with your idea completely.', 'rozi bo''lmoq'),
  ('angry', 1, 'g''azablangan, jahli chiqqan', 'He was angry when he missed the bus.', 'g''azablangan'),
  ('arrive', 1, 'yetib kelmoq, kelmoq', 'The train will arrive at noon.', 'yetib kelmoq'),
  ('attack', 1, 'hujum qilmoq, hujum', 'The dog tried to attack the cat.', 'hujum qilmoq'),
  ('bottom', 1, 'pastki qism, tub', 'The key was at the bottom of the bag.', 'pastki qism'),
  ('clever', 1, 'aqlli, zukko', 'She is a clever student who solves problems quickly.', 'aqlli'),
  ('cruel', 1, 'shafqatsiz, qo''pol', 'It is cruel to leave animals outside in cold weather.', 'shafqatsiz'),
  ('finally', 1, 'nihoyat, oxir-oqibat', 'After hours of waiting, the bus finally came.', 'nihoyat'),
  ('hide', 1, 'yashirmoq, berkitmoq', 'The children like to hide behind the sofa.', 'yashirmoq'),
  ('hunt', 1, 'ov qilmoq, qidirmoq', 'Farmers used to hunt animals for food.', 'ov qilmoq'),
  ('lot', 1, 'ko''p, juda ko''p', 'There are a lot of books in this library.', 'ko''p'),
  ('middle', 1, 'o''rta, markaziy qism', 'She sat in the middle of the room.', 'o''rta'),
  ('moment', 1, 'lahza, bir zum', 'Please wait a moment while I check.', 'lahza'),
  ('pleased', 1, 'xursand, mamnun', 'She was pleased with her exam results.', 'xursand'),
  ('promise', 1, 'va''da bermoq, so''z bermoq', 'He promised to come on time tomorrow.', 'va''da bermoq'),
  ('reply', 1, 'javob bermoq, javob', 'She did not reply to my message.', 'javob bermoq'),
  ('safe', 1, 'xavfsiz, omon', 'Always keep your passport in a safe place.', 'xavfsiz'),
  ('trick', 1, 'hiyla, fokus', 'The rabbit played a clever trick on the lion.', 'hiyla'),
  ('well', 1, 'yaxshi, sog''lom; quduq', 'She speaks English very well.', 'yaxshi'),
  ('adventure', 2, 'sarguzasht, qo''zg''alish', 'Climbing the mountain was a great adventure.', 'sarguzasht'),
  ('approach', 2, 'yaqinlashmoq, usul', 'A strange dog approached us slowly.', 'yaqinlashmoq'),
  ('carefully', 2, 'ehtiyotkorlik bilan, diqqat bilan', 'Read the instructions carefully before starting.', 'ehtiyotkorlik bilan'),
  ('chemical', 2, 'kimyoviy modda, kimyoviy', 'Do not mix these two chemicals together.', 'kimyoviy modda'),
  ('create', 2, 'yaratmoq, hosil qilmoq', 'She created a beautiful painting last week.', 'yaratmoq'),
  ('evil', 2, 'yovuz, yomon', 'The villain in the story was truly evil.', 'yovuz'),
  ('experiment', 2, 'tajriba, sinov', 'The students did an experiment in the lab.', 'tajriba'),
  ('kill', 2, 'o''ldirmoq, yo''q qilmoq', 'The frost killed all the plants in the garden.', 'o''ldirmoq'),
  ('laboratory', 2, 'laboratoriya, tajribaxona', 'Scientists work in a laboratory every day.', 'laboratoriya'),
  ('laugh', 2, 'kulmoq, kulgu', 'Everyone laughed at the funny joke.', 'kulmoq'),
  ('loud', 2, 'baland ovozli, shovqinli', 'The music was too loud at the party.', 'baland ovozli'),
  ('nervous', 2, 'asabiy, xavotirli', 'She felt nervous before the big exam.', 'asabiy'),
  ('noise', 2, 'shovqin, ovoz', 'The children made a lot of noise outside.', 'shovqin'),
  ('project', 2, 'loyiha, reja', 'We worked on a science project together.', 'loyiha'),
  ('scare', 2, 'qo''rqitmoq, vahimaga solmoq', 'Loud thunder can scare small children.', 'qo''rqitmoq'),
  ('secret', 2, 'sir, maxfiy', 'Can you keep a secret? I have good news.', 'sir'),
  ('shout', 2, 'baqirmoq, qichqirmoq', 'Do not shout in the library, please.', 'baqirmoq'),
  ('smell', 2, 'hid, hidlamoq', 'The flowers smell very sweet in spring.', 'hid'),
  ('terrible', 2, 'dahshatli, juda yomon', 'The weather was terrible during the storm.', 'dahshatli'),
  ('worse', 2, 'yomonroq, battar', 'My cold is getting worse every day.', 'yomonroq'),
  ('alien', 3, 'begona, kosmoslik mavjudot', 'The movie was about an alien from another planet.', 'begona'),
  ('among', 3, 'orasida, ichida', 'She was the best student among all her classmates.', 'orasida'),
  ('chart', 3, 'jadval, diagramma', 'The teacher drew a chart on the board.', 'jadval'),
  ('cloud', 3, 'bulut, to''da', 'Dark clouds appeared before the rain started.', 'bulut'),
  ('comprehend', 3, 'tushunmoq, anglash', 'It is hard to comprehend this difficult text.', 'tushunmoq'),
  ('describe', 3, 'tasvirlamoq, ta''riflamoq', 'Please describe what you saw at the scene.', 'tasvirlamoq'),
  ('ever', 3, 'hech qachon, doimo', 'Have you ever visited another country before?', 'hech qachon'),
  ('fail', 3, 'muvaffaqiyatsiz bo''lmoq, rad etmoq', 'He failed the test and studied harder next time.', 'muvaffaqiyatsiz bo''lmoq'),
  ('friendly', 3, 'do''stona, mehribon', 'The new teacher was very friendly to everyone.', 'do''stona'),
  ('grade', 3, 'baho, daraja', 'She got a high grade on her English test.', 'baho'),
  ('instead', 3, 'o''rniga, buning o''rniga', 'I ordered tea instead of coffee today.', 'o''rniga'),
  ('library', 3, 'kutubxona, kitoblar to''plami', 'I borrow books from the library every week.', 'kutubxona'),
  ('planet', 3, 'sayyora, dunyo', 'Earth is the third planet from the Sun.', 'sayyora'),
  ('report', 3, 'hisobot, xabar bermoq', 'He wrote a report about climate change.', 'hisobot'),
  ('several', 3, 'bir nechta, bir qancha', 'I have visited that museum several times.', 'bir nechta'),
  ('solve', 3, 'hal qilmoq, echmoq', 'Can you solve this math problem for me?', 'hal qilmoq'),
  ('suddenly', 3, 'to''satdan, birdan', 'The lights suddenly went out during dinner.', 'to''satdan'),
  ('suppose', 3, 'faraz qilmoq, o''ylash', 'I suppose the meeting will start at nine.', 'faraz qilmoq'),
  ('universe', 3, 'koinot, borliq', 'Scientists study the universe to learn its secrets.', 'koinot'),
  ('view', 3, 'ko''rinish, manzara; qarash', 'The view from the mountain top was amazing.', 'ko''rinish'),
  ('appropriate', 4, 'mos, to''g''ri, maqsadga muvofiq', 'That dress is not appropriate for a job interview.', 'mos'),
  ('avoid', 4, 'qochmoq, oldini olmoq', 'You should avoid eating too much sugar.', 'qochmoq'),
  ('behave', 4, 'o''zini tutmoq, xulq-atvor', 'Children should behave well in public places.', 'o''zini tutmoq'),
  ('calm', 4, 'tinch, sokin, xotirjam', 'She stayed calm during the difficult situation.', 'tinch'),
  ('concern', 4, 'tashvish, qaygu; qiziqtirmoq', 'His poor health is a concern for the family.', 'tashvish'),
  ('content', 4, 'mazmun; mamnun, rozi', 'She was content with her simple life.', 'mazmun; mamnun'),
  ('expect', 4, 'kutmoq, umid qilmoq', 'I expect the package to arrive tomorrow.', 'kutmoq'),
  ('frequently', 4, 'tez-tez, ko''p marta', 'He frequently visits his grandparents on weekends.', 'tez-tez'),
  ('habit', 4, 'odat, rasm', 'Reading before bed is a good habit.', 'odat'),
  ('instruct', 4, 'o''rgatmoq, yo''riqnoma bermoq', 'The teacher instructed students to open their books.', 'o''rgatmoq'),
  ('issue', 4, 'masala, muammo; chiqarmoq', 'The main issue is the lack of clean water.', 'masala'),
  ('none', 4, 'hech biri, hech qaysi', 'None of the students passed the final exam.', 'hech biri'),
  ('patient', 4, 'sabr-qanoatli, bemor', 'You need to be patient when learning a language.', 'sabr-qanoatli'),
  ('positive', 4, 'ijobiy, musbat', 'Try to think in a positive way every day.', 'ijobiy'),
  ('punish', 4, 'jazolash, jazolamoq', 'Parents should not punish children too harshly.', 'jazolash'),
  ('represent', 4, 'vakil bo''lmoq, ifodalash', 'She was chosen to represent her school.', 'vakil bo''lmoq'),
  ('shake', 4, 'silkimoq, qaltiramoq', 'He shook her hand and introduced himself.', 'silkimoq'),
  ('spread', 4, 'tarqalmoq, yoyilmoq', 'News spreads very quickly on social media.', 'tarqalmoq'),
  ('stroll', 4, 'sekin yurmoq, sayr qilmoq', 'We took a stroll in the park after dinner.', 'sekin yurmoq'),
  ('village', 4, 'qishloq, mahalla', 'She grew up in a small village in the mountains.', 'qishloq'),
  ('aware', 5, 'xabardor, bilimli', 'Are you aware of the new school rules?', 'xabardor'),
  ('badly', 5, 'yomon ravishda, juda qattiq', 'He was badly injured in the accident.', 'yomon ravishda'),
  ('belong', 5, 'tegishli bo''lmoq, a''zo bo''lmoq', 'This book belongs to the school library.', 'tegishli bo''lmoq'),
  ('continue', 5, 'davom ettirmoq, to''xtatmasdan', 'Please continue reading from page ten.', 'davom ettirmoq'),
  ('error', 5, 'xato, yanglishish', 'There was an error in the computer program.', 'xato'),
  ('experience', 5, 'tajriba, kuzatish', 'She has ten years of teaching experience.', 'tajriba'),
  ('field', 5, 'maydon, soha', 'He works in the field of medicine.', 'maydon'),
  ('hurt', 5, 'og''riq, jarohatlash; azob bermoq', 'She hurt her knee while playing football.', 'og''riq'),
  ('judgment', 5, 'hukm, baho; ko''rish qobiliyati', 'Use good judgment when making big decisions.', 'hukm'),
  ('likely', 5, 'ehtimol, mumkin', 'It is likely to rain tomorrow afternoon.', 'ehtimol'),
  ('normal', 5, 'oddiy, me''yoriy', 'It is normal to feel nervous before exams.', 'oddiy'),
  ('rare', 5, 'kam uchraydigan, noyob', 'Snow is very rare in this part of the country.', 'kam uchraydigan'),
  ('relax', 5, 'dam olmoq, bo''shashtirmoq', 'I like to relax by listening to music.', 'dam olmoq'),
  ('request', 5, 'so''rov, iltimos; so''ramoq', 'She made a request to change her seat.', 'so''rov'),
  ('reside', 5, 'yashash, istiqomat qilish', 'He resides in a small apartment near the park.', 'yashash'),
  ('result', 5, 'natija, oqibat', 'The result of the test will come tomorrow.', 'natija'),
  ('roll', 5, 'dumalash, buralmoq', 'The ball rolled down the hill quickly.', 'dumalash'),
  ('since', 5, 'beri, chunki, shu vaqtdan', 'She has lived here since she was a child.', 'beri'),
  ('visible', 5, 'ko''rinadigan, ko''zga tashlanadigan', 'The stars are not visible on cloudy nights.', 'ko''rinadigan'),
  ('wild', 5, 'yovvoyi, qo''pol; dahshatli', 'Wild animals should not be kept as pets.', 'yovvoyi'),
  ('advantage', 6, 'ustunlik, foyda', 'Knowing two languages is a great advantage.', 'ustunlik'),
  ('cause', 6, 'sabab, turtki; sabab bo''lmoq', 'What was the cause of the fire last night?', 'sabab'),
  ('choice', 6, 'tanlov, imkoniyat', 'You have the choice to study any subject.', 'tanlov'),
  ('community', 6, 'jamoa, mahalla; jamoat', 'The whole community helped after the flood.', 'jamoa'),
  ('dead', 6, 'o''lik, hayotsiz', 'The plant died because nobody watered it.', 'o''lik'),
  ('distance', 6, 'masofa, uzoqlik', 'The distance between the two cities is 200 km.', 'masofa'),
  ('escape', 6, 'qochmoq, chiqib ketmoq', 'The bird managed to escape from its cage.', 'qochmoq'),
  ('face', 6, 'yuz, bet; duch kelmoq', 'She had to face many challenges in life.', 'yuz'),
  ('follow', 6, 'ergashmoq, izidan bormoq', 'Follow the instructions on the board.', 'ergashmoq'),
  ('fright', 6, 'qo''rquv, dahshat', 'The loud bang gave everyone a big fright.', 'qo''rquv'),
  ('ghost', 6, 'arvoh, ruh', 'Some people believe that ghosts exist.', 'arvoh'),
  ('individual', 6, 'shaxs, alohida; individual', 'Each individual student has different needs.', 'shaxs'),
  ('pet', 6, 'uy hayvoni, sevimli', 'She has a pet rabbit that she loves dearly.', 'uy hayvoni'),
  ('reach', 6, 'yetib bormoq, qo''l yetmoq', 'He reached the top of the mountain by noon.', 'yetib bormoq'),
  ('return', 6, 'qaytmoq, qaytarmoq', 'I will return the book to the library today.', 'qaytmoq'),
  ('survive', 6, 'omon qolmoq, saqlanib qolmoq', 'The plant survived despite the cold weather.', 'omon qolmoq'),
  ('upset', 6, 'xafa, bezovta; buzmoq', 'She was upset when she lost her phone.', 'xafa'),
  ('voice', 6, 'ovoz, so''z; fikr', 'She has a beautiful singing voice.', 'ovoz'),
  ('weather', 6, 'ob-havo, havo sharoiti', 'The weather today is sunny and warm.', 'ob-havo'),
  ('wise', 6, 'dono, aqliy', 'It is wise to save money for the future.', 'dono'),
  ('allow', 7, 'ruxsat bermoq, imkon bermoq', 'Parents do not allow children to stay up late.', 'ruxsat bermoq'),
  ('announce', 7, 'e''lon qilmoq, xabar bermoq', 'The teacher announced the exam results today.', 'e''lon qilmoq'),
  ('beside', 7, 'yonida, qoshida', 'She sat beside her best friend in class.', 'yonida'),
  ('challenge', 7, 'qiyinchilik, sinovdan o''tkazmoq', 'Learning a new language is a great challenge.', 'qiyinchilik'),
  ('claim', 7, 'da''vo qilmoq, talab qilmoq', 'He claimed that he did not take the money.', 'da''vo qilmoq'),
  ('condition', 7, 'holat, shart; sharoit', 'The patient is in a stable condition now.', 'holat'),
  ('contribute', 7, 'hissa qo''shmoq, yordam bermoq', 'Everyone should contribute to keeping the city clean.', 'hissa qo''shmoq'),
  ('difference', 7, 'farq, tafovut', 'What is the difference between these two words?', 'farq'),
  ('divide', 7, 'bo''lmoq, ajratmoq', 'Divide the class into four equal groups.', 'bo''lmoq'),
  ('expert', 7, 'mutaxassis, bilimdon', 'She is an expert in computer programming.', 'mutaxassis'),
  ('famous', 7, 'mashhur, taniqli', 'This city is famous for its beautiful old buildings.', 'mashhur'),
  ('force', 7, 'kuch, majburlamoq', 'Do not force anyone to do something against their will.', 'kuch'),
  ('harm', 7, 'zarar, shikast; zarar yetkazmoq', 'Smoking can cause serious harm to your health.', 'zarar'),
  ('lay', 7, 'qo''ymoq, yotqizmoq', 'She laid the book on the table carefully.', 'qo''ymoq'),
  ('peace', 7, 'tinchlik, osoyishtalik', 'After the war, people finally lived in peace.', 'tinchlik'),
  ('prince', 7, 'shahzoda, knyaz', 'The prince rode his horse through the forest.', 'shahzoda'),
  ('protect', 7, 'himoya qilmoq, asramoq', 'Wear sunscreen to protect your skin from the sun.', 'himoya qilmoq'),
  ('sense', 7, 'his, tuygu; manto', 'It makes sense to study every day.', 'his'),
  ('sudden', 7, 'to''satdan bo''ladigan, kutilmagan', 'There was a sudden change in the weather.', 'to''satdan bo''ladigan'),
  ('therefore', 7, 'shuning uchun, demak', 'He studied hard; therefore, he passed the exam.', 'shuning uchun'),
  ('accept', 8, 'qabul qilmoq, rozilik bildirmoq', 'She accepted the job offer with great joy.', 'qabul qilmoq'),
  ('arrange', 8, 'tartibga solmoq, tashkil etmoq', 'He arranged all the books on the shelf neatly.', 'tartibga solmoq'),
  ('attend', 8, 'qatnashmoq, bormoq', 'All students must attend the morning assembly.', 'qatnashmoq'),
  ('balance', 8, 'muvozanat, balans; tenglashtirmoq', 'A healthy diet helps maintain a good balance.', 'muvozanat'),
  ('contrast', 8, 'farq, qarama-qarshilik', 'There is a strong contrast between the two paintings.', 'farq'),
  ('encourage', 8, 'rag''batlantirmoq, ruhlantirmoq', 'Teachers should encourage students to ask questions.', 'rag''batlantirmoq'),
  ('familiar', 8, 'tanish, oddiy, ma''lum', 'Are you familiar with this type of question?', 'tanish'),
  ('grab', 8, 'changallamoq, ushlamoq', 'She grabbed her bag and ran to the bus.', 'changallamoq'),
  ('hang', 8, 'osmoq, ilinmoq', 'Please hang your coat on the hook by the door.', 'osmoq'),
  ('huge', 8, 'ulkan, katta', 'The new shopping mall is huge inside.', 'ulkan'),
  ('necessary', 8, 'zarur, kerakli', 'It is necessary to drink enough water daily.', 'zarur'),
  ('pattern', 8, 'naqsh, shakl; namuna', 'The dress has a beautiful flower pattern.', 'naqsh'),
  ('propose', 8, 'taklif qilmoq, taklif', 'He proposed a new solution to the problem.', 'taklif qilmoq'),
  ('purpose', 8, 'maqsad, niyat', 'What is the purpose of this meeting today?', 'maqsad'),
  ('release', 8, 'ozod qilmoq, chiqarmoq', 'The singer will release a new album next month.', 'ozod qilmoq'),
  ('require', 8, 'talab qilmoq, kerak bo''lmoq', 'This job requires five years of experience.', 'talab qilmoq'),
  ('single', 8, 'yagona, bitta; yolg''iz', 'There was not a single cloud in the sky.', 'yagona'),
  ('success', 8, 'muvaffaqiyat, erishish', 'Hard work is the key to success in life.', 'muvaffaqiyat'),
  ('tear', 8, 'yirtmoq; ko''z yoshi', 'She tore the old paper into small pieces.', 'yirtmoq; ko''z yoshi'),
  ('theory', 8, 'nazariya, faraziya', 'Einstein developed the theory of relativity.', 'nazariya'),
  ('against', 9, 'qarshi, zid', 'She voted against the new school rule.', 'qarshi'),
  ('beach', 9, 'qirg''oq, plyaj', 'We spent the day relaxing on the beach.', 'qirg''oq'),
  ('damage', 9, 'zarar, shikast; zarar yetkazmoq', 'The storm caused serious damage to the village.', 'zarar'),
  ('discover', 9, 'kashf etmoq, topmoq', 'Columbus discovered America in 1492.', 'kashf etmoq'),
  ('emotion', 9, 'his-tuygu, kechinma', 'Music can express many different emotions.', 'his-tuygu'),
  ('fix', 9, 'tuzatmoq, mahkamlamoq', 'Can you fix the broken chair leg?', 'tuzatmoq'),
  ('frank', 9, 'ochiq, samimiy, to''g''ri so''z', 'She was frank about her feelings and concerns.', 'ochiq'),
  ('identify', 9, 'aniqlash, tanib olmoq', 'Can you identify the problem in this sentence?', 'aniqlash'),
  ('island', 9, 'orol, alohida joy', 'They traveled to a small island for vacation.', 'orol'),
  ('ocean', 9, 'okean, dengiz', 'The Pacific Ocean is the largest ocean on Earth.', 'okean'),
  ('perhaps', 9, 'balki, ehtimol', 'Perhaps we can meet again next week.', 'balki'),
  ('pleasant', 9, 'yoqimli, qulay', 'The spring weather is always very pleasant.', 'yoqimli'),
  ('prevent', 9, 'oldini olmoq, to''sish', 'Washing hands helps prevent the spread of germs.', 'oldini olmoq'),
  ('rock', 9, 'tosh, qoya; tebratmoq', 'She sat on a large rock by the river.', 'tosh'),
  ('save', 9, 'tejash, saqlash; qutqarmoq', 'Try to save some money for emergencies.', 'tejash'),
  ('step', 9, 'qadam, daraja; qadam bosmoq', 'Take one step at a time when solving problems.', 'qadam'),
  ('still', 9, 'hali ham; tinch, jim', 'She still has not received an answer to her email.', 'hali ham; tinch'),
  ('taste', 9, 'ta''m, maza; tatib ko''rmoq', 'This soup has a wonderful taste.', 'ta''m'),
  ('throw', 9, 'uloqtirmoq, otmoq', 'He threw the ball to his teammate.', 'uloqtirmoq'),
  ('wave', 9, 'to''lqin; qo''l siltamoq', 'She waved goodbye as the train left the station.', 'to''lqin; qo''l siltamoq'),
  ('benefit', 10, 'foyda, manfaat; foyda ko''rmoq', 'Exercise has many health benefits.', 'foyda'),
  ('certain', 10, 'aniq, ishonchli; ba''zi', 'I am certain that she will pass the test.', 'aniq'),
  ('chance', 10, 'imkoniyat, ehtimol; tasodif', 'Give everyone a chance to speak in class.', 'imkoniyat'),
  ('effect', 10, 'ta''sir, natija; ta''sir etmoq', 'The medicine had a positive effect on the patient.', 'ta''sir'),
  ('essential', 10, 'zaruriy, asosiy, muhim', 'Water is essential for all living things.', 'zaruriy'),
  ('far', 10, 'uzoq, uzoqda', 'The school is not far from our house.', 'uzoq'),
  ('focus', 10, 'e''tibor bermoq, diqqatni jamlash', 'Try to focus on one task at a time.', 'e''tibor bermoq'),
  ('function', 10, 'vazifa, funksiya; ishlash', 'What is the function of the kidney in the body?', 'vazifa'),
  ('grass', 10, 'o''t, maysazor', 'The children played on the green grass.', 'o''t'),
  ('guard', 10, 'qorovul, himoya; himoya qilmoq', 'A security guard stands at the entrance.', 'qorovul'),
  ('image', 10, 'tasvir, rasm; obro''', 'The camera captures a clear image.', 'tasvir'),
  ('immediate', 10, 'darhol, zudlik bilan', 'The problem requires an immediate solution.', 'darhol'),
  ('primary', 10, 'asosiy, birinchi', 'Her primary goal is to finish university.', 'asosiy'),
  ('proud', 10, 'faxrli, maqtanuvchi', 'Her parents were proud of her achievements.', 'faxrli'),
  ('remain', 10, 'qolmoq, saqlanmoq', 'Only a few students remained after class.', 'qolmoq'),
  ('rest', 10, 'dam olish; qolgan qismi', 'You need to rest after working so hard.', 'dam olish; qolgan qismi'),
  ('separate', 10, 'ajratmoq, bo''lish; alohida', 'Please separate the colored clothes from white ones.', 'ajratmoq'),
  ('site', 10, 'joy, o''rin; veb-sayt', 'The construction site was busy all day.', 'joy'),
  ('tail', 10, 'dum; quyruq', 'The dog wagged its tail happily.', 'dum; quyruq'),
  ('trouble', 10, 'muammo, qiyinchilik; bezovta qilmoq', 'He got into trouble for arriving late.', 'muammo');
